(()=>{
'use strict';
const TZ='Europe/Bucharest';
const hotels=[
 {from:19,to:22,name:'Hotel Orizont Predeal',phone:'+40734458554',phoneLabel:'+40 734 458 554',query:'Hotel Orizont Predeal Romania',meta:'19–23.9 · פרדיאל'},
 {from:23,to:26,name:'Swissôtel Poiana Brașov',phone:'+40368520500',phoneLabel:'+40 368 520 500',query:'Swissotel Poiana Brasov Romania',meta:'23–27.9 · פויאנה בראשוב'},
 {from:27,to:29,name:'Novotel Bucharest City Centre',phone:'+40213088505',phoneLabel:'+40 21 308 8505',query:'Novotel Bucharest City Centre Romania',meta:'27–30.9 · בוקרשט'}
];
function localParts(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date());const g=t=>Number(p.find(x=>x.type===t)?.value||0);return{y:g('year'),m:g('month'),d:g('day'),h:g('hour'),min:g('minute')}}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function mapUrl(q){return 'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q)}
function topNav(page){const b=document.querySelector(`header .nav button[data-page="${page}"]`);if(b)b.click()}
function injectStyle(){if(document.getElementById('appShellStyle'))return;const s=document.createElement('style');s.id='appShellStyle';s.textContent=`
:root{--app-blue:#2563eb;--app-blue-dark:#1d4ed8;--app-blue-soft:#eff6ff}
#homeToday{position:relative;gap:0!important;padding-right:4px}
#homeToday .home-item{position:relative;margin:0 18px 0 0!important;border:0!important;border-right:2px solid #bfdbfe!important;border-radius:0!important;padding:10px 16px 12px 10px!important;background:transparent!important}
#homeToday .home-item:before{content:'';position:absolute;right:-6px;top:17px;width:10px;height:10px;border-radius:50%;background:var(--app-blue);box-shadow:0 0 0 4px var(--card,#fff)}
#homeToday .home-item:first-child{margin:0!important;border:1px solid var(--line,#d8e3e7)!important;border-radius:12px!important;padding:11px!important;background:var(--app-blue-soft)!important}
#homeToday .home-item:first-child:before{display:none}
#homeToday .home-item:last-child{padding-bottom:6px!important}
#homeSmartPanel{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:14px 0}
.home-smart-card{background:var(--card,#fff);border:1px solid var(--line,#d8e3e7);border-radius:16px;padding:14px}
.home-smart-card h3{margin:0 0 9px;font-size:1rem}.home-smart-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.home-smart-actions a,.home-smart-actions button{border:0;border-radius:9px;padding:8px 10px;background:var(--app-blue);color:#fff;text-decoration:none;font-weight:800;font-size:.86rem;cursor:pointer}
.home-quick-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.home-quick{border:1px solid var(--line,#d8e3e7);border-radius:12px;background:var(--card,#fff);color:var(--text,#17313b);padding:12px 7px;text-align:center;font-weight:800;cursor:pointer}.home-quick span{display:block;font-size:1.25rem;margin-bottom:3px}
#mobileDock,#moreSheet,#nextNavFab{display:none}
@media(max-width:850px){
 body{padding-bottom:78px!important}.wrap{padding-bottom:100px!important}.head{padding-bottom:5px!important}header .nav{display:flex!important;width:100%!important;overflow-x:auto!important;overflow-y:hidden!important;flex-wrap:nowrap!important;gap:5px!important;padding:3px 0 5px!important;scrollbar-width:none!important}header .nav::-webkit-scrollbar{display:none!important}header .nav button{display:inline-flex!important;flex:0 0 auto!important;background:#ffffff16!important;color:#fff!important;border:1px solid #ffffff45!important}header .nav button.on{background:#fff!important;color:var(--app-blue-dark)!important;border-color:#fff!important}
 #homeSmartPanel{grid-template-columns:1fr}.home-quick-grid{grid-template-columns:repeat(4,1fr)}.home-quick{font-size:.72rem;padding:9px 3px}.home-quick span{font-size:1.15rem}
 #mobileDock{position:fixed;display:grid;grid-template-columns:repeat(4,1fr);left:8px;right:8px;bottom:max(8px,env(safe-area-inset-bottom));z-index:3900;background:color-mix(in srgb,var(--card,#fff) 94%,transparent);border:1px solid var(--line,#d8e3e7);border-radius:18px;padding:6px;box-shadow:0 8px 28px #0003;backdrop-filter:blur(14px)}
 #mobileDock button{border:0;background:transparent;color:var(--muted,#667983);font-size:11px;font-weight:800;padding:5px 2px;border-radius:12px;line-height:1.15}#mobileDock button span{display:block;font-size:20px;margin-bottom:2px}#mobileDock button.on{background:var(--app-blue-soft);color:var(--app-blue-dark)}
 #moreSheet{display:none;position:fixed;inset:0;z-index:4100;background:#0008;align-items:flex-end}#moreSheet.open{display:flex}#moreSheet .sheet{width:100%;background:var(--card,#fff);color:var(--text,#17313b);border-radius:22px 22px 0 0;padding:14px 14px calc(18px + env(safe-area-inset-bottom));box-shadow:0 -10px 30px #0004}#moreSheet .grab{width:42px;height:4px;background:var(--line,#d8e3e7);border-radius:99px;margin:0 auto 12px}#moreSheet h3{margin:0 0 12px}.more-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.more-grid button{border:1px solid var(--line,#d8e3e7);background:var(--soft,#eef6f8);color:var(--text,#17313b);border-radius:13px;padding:12px 6px;font-weight:800}.more-grid button span{display:block;font-size:22px;margin-bottom:3px}
 #nextNavFab{display:none;position:fixed;left:14px;bottom:88px;z-index:3800;background:var(--app-blue);color:#fff;border:0;border-radius:999px;padding:11px 15px;font-weight:900;box-shadow:0 8px 22px #0004;text-decoration:none}#nextNavFab.show{display:block}
 #page-home .home-grid{display:block!important}#page-home .home-grid>div:last-child{margin-top:14px}#page-home #homeDays{max-height:330px;overflow:auto}
}
:root[data-theme="dark"] #mobileDock{background:#111827f2;border-color:#334155}:root[data-theme="dark"] #mobileDock button.on{background:#1e3a8a;color:#dbeafe}:root[data-theme="dark"] #moreSheet .sheet,:root[data-theme="dark"] .home-smart-card,:root[data-theme="dark"] .home-quick{background:#111827;color:#f8fafc;border-color:#334155}:root[data-theme="dark"] #moreSheet .more-grid button{background:#1e293b;color:#f8fafc;border-color:#334155}:root[data-theme="dark"] #homeToday .home-item:first-child{background:#172554!important}
`;document.head.appendChild(s)}
function currentHotel(){const x=localParts();if(x.y!==2026||x.m!==9)return null;return hotels.find(h=>x.d>=h.from&&x.d<=h.to)||null}
function todayDay(){const x=localParts();if(x.y!==2026||x.m!==9||x.d<19||x.d>30)return null;const arr=(typeof D!=='undefined'&&Array.isArray(D))?D:null;return arr?.[x.d-19]||null}
function parseMinutes(t){const m=String(t||'').match(/(\d{1,2}):(\d{2})/);return m?Number(m[1])*60+Number(m[2]):null}
function nextStop(){const x=localParts();if(x.y===2026&&x.m===9&&x.d===18)return{place:'Ben Gurion Airport Terminal 3',label:'נתב״ג Terminal 3'};const day=todayDay();if(!day||!Array.isArray(day.s))return null;const now=x.h*60+x.min;let fallback=null;for(const s of day.s){const place=s?.[0]||'',time=s?.[3]||'',desc=s?.[4]||'';if(!place)continue;fallback={place,label:place,desc};const mins=parseMinutes(time);if(mins!==null&&mins>=now-20)return fallback}return fallback}
function buildSmartHome(){const home=document.getElementById('page-home');if(!home)return;let panel=document.getElementById('homeSmartPanel');if(!panel){panel=document.createElement('div');panel.id='homeSmartPanel';const grid=home.querySelector('.home-grid');(grid||home).insertBefore(panel,(grid||home).firstChild)}const hotel=currentHotel();const next=nextStop();const hotelHtml=hotel?`<div class="home-smart-card"><h3>🏨 המלון של היום</h3><b>${esc(hotel.name)}</b><div class="muted">${esc(hotel.meta)}</div><div class="home-smart-actions"><a target="_blank" href="${mapUrl(hotel.query)}">📍 ניווט</a><a href="tel:${hotel.phone}">📞 התקשר</a><button data-go="hotels">ℹ️ פרטים</button></div></div>`:`<div class="home-smart-card"><h3>🏨 לינה</h3><b>${localParts().d<19?'Hotel Orizont Predeal':'פרטי המלונות'}</b><div class="muted">כל ההזמנות, כתובות וטלפונים במקום אחד</div><div class="home-smart-actions"><button data-go="hotels">פתח מלונות</button></div></div>`;panel.innerHTML=`${hotelHtml}<div class="home-smart-card"><h3>⚡ פעולות מהירות</h3><div class="home-quick-grid"><button class="home-quick" data-go="trip"><span>🧭</span>מסלול</button><button class="home-quick" data-go="hotels"><span>🏨</span>מלון</button><button class="home-quick" data-go="emergency"><span>🆘</span>חשוב</button><button class="home-quick" data-weather><span>🌦️</span>מזג אוויר</button></div>${next?`<div class="home-smart-actions"><a target="_blank" href="${mapUrl(next.place)}">🚗 ניווט ליעד הבא · ${esc(next.label)}</a></div>`:''}</div>`;panel.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>topNav(b.dataset.go));panel.querySelector('[data-weather]')?.addEventListener('click',()=>topNav('trip'))}
function buildDock(){if(document.getElementById('mobileDock'))return;const d=document.createElement('nav');d.id='mobileDock';d.innerHTML=`<button data-dock="home"><span>🏠</span>ראשי</button><button data-dock="trip"><span>🧭</span>מסלול</button><button data-dock="hotels"><span>🏨</span>לינה</button><button data-more><span>•••</span>עוד</button>`;document.body.appendChild(d);d.querySelectorAll('[data-dock]').forEach(b=>b.onclick=()=>topNav(b.dataset.dock));d.querySelector('[data-more]').onclick=()=>document.getElementById('moreSheet')?.classList.add('open')}
function buildMore(){if(document.getElementById('moreSheet'))return;const m=document.createElement('div');m.id='moreSheet';m.innerHTML=`<div class="sheet"><div class="grab"></div><h3>עוד</h3><div class="more-grid"><button data-go="car"><span>🚙</span>רכב</button><button data-go="checkin"><span>✈️</span>צ׳ק־אין</button><button data-go="todo"><span>✅</span>משימות</button><button data-go="calculator"><span>🧮</span>מחשבון</button><button data-go="summary"><span>💰</span>סיכום</button><button data-go="emergency"><span>🆘</span>חשוב</button><button data-theme><span>🌙</span>יום / לילה</button></div></div>`;document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open')});m.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{m.classList.remove('open');topNav(b.dataset.go)});m.querySelector('[data-theme]').onclick=()=>document.getElementById('themeToggleBtn')?.click()}
function updateDock(){const on=document.querySelector('.page.on')?.id?.replace('page-','')||'home';document.querySelectorAll('#mobileDock [data-dock]').forEach(b=>b.classList.toggle('on',b.dataset.dock===on));if(!['home','trip','hotels'].includes(on))document.querySelector('#mobileDock [data-more]')?.classList.add('on');else document.querySelector('#mobileDock [data-more]')?.classList.remove('on')}
function updateFab(){let a=document.getElementById('nextNavFab');if(!a){a=document.createElement('a');a.id='nextNavFab';a.target='_blank';document.body.appendChild(a)}const n=nextStop(),home=document.getElementById('page-home')?.classList.contains('on');if(n&&home){a.href=mapUrl(n.place);a.textContent='🧭 ניווט ליעד הבא';a.classList.add('show')}else a.classList.remove('show')}
function refresh(){buildSmartHome();updateDock();updateFab()}
function init(){injectStyle();buildDock();buildMore();refresh();setTimeout(refresh,500);setTimeout(refresh,1400);document.addEventListener('click',e=>{if(e.target.closest('header .nav button[data-page]'))setTimeout(refresh,50)},true);window.addEventListener('storage',refresh)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();