(()=>{
'use strict';
const INS_KEY='romania-travel-insurance-v1';
const style=document.createElement('style');style.textContent=`.emergency-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.emergency-card{background:#fff;border:1px solid var(--line,#d8e3e7);border-radius:14px;padding:14px}.emergency-card h3{margin:0 0 8px}.emergency-number{font-size:1.45rem;font-weight:900;color:var(--p,#0d6f88);direction:ltr;unicode-bidi:isolate}.emergency-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:9px}.emergency-actions a,.emergency-actions button{display:inline-block;background:var(--p,#0d6f88);color:#fff;border:0;border-radius:9px;padding:8px 10px;text-decoration:none;cursor:pointer}.flight-row{padding:9px 0;border-bottom:1px solid #e8eef0}.flight-row:last-child{border-bottom:0}@media(max-width:850px){.emergency-grid{grid-template-columns:1fr}}`;document.head.appendChild(style);
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function navBtn(){const nav=document.querySelector('.nav');if(!nav||nav.querySelector('[data-page="emergency"]'))return;const b=document.createElement('button');b.dataset.page='emergency';b.textContent='🆘 חשוב';nav.appendChild(b)}
function loadInsurance(){try{return JSON.parse(localStorage.getItem(INS_KEY)||'{}')}catch(e){return {}}}
function saveInsurance(){const v={company:document.getElementById('insCompany')?.value.trim()||'',policy:document.getElementById('insPolicy')?.value.trim()||'',phone:document.getElementById('insPhone')?.value.trim()||''};localStorage.setItem(INS_KEY,JSON.stringify(v));const s=document.getElementById('insStatus');if(s){s.textContent='✅ נשמר';setTimeout(()=>s.textContent='',1600)}}
function build(){if(document.getElementById('page-emergency'))return;const main=document.querySelector('main.wrap');if(!main)return;const v=loadInsurance(),s=document.createElement('section');s.id='page-emergency';s.className='page';s.innerHTML=`<h1>🆘 Emergency / מידע חשוב</h1><div class="emergency-grid"><div class="emergency-card"><h3>🚙 Klass Wagen · 24/7</h3><div class="emergency-number">+40 374 020 002</div><p>מספר הזמנה: <span class="ltr"><b>OTP-2468182759765</b></span><br>טיסה אצל Klass Wagen: <span class="ltr"><b>LY9491</b></span></p><div class="emergency-actions"><a href="tel:+40374020002">📞 התקשר</a></div></div><div class="emergency-card"><h3>🏨 Swissôtel Poiana Brașov</h3><div class="emergency-number">+40 368 520 500</div><div class="emergency-actions"><a href="tel:+40368520500">📞 התקשר</a><a target="_blank" href="https://www.google.com/maps/search/?api=1&query=Swissotel+Poiana+Brasov+9+Drumul+Sulinar">📍 מפה</a></div></div><div class="emergency-card"><h3>🏨 Novotel Bucharest City Centre</h3><div class="emergency-number">+40 21 308 8505</div><div class="emergency-actions"><a href="tel:+40213088505">📞 התקשר</a><a target="_blank" href="https://www.google.com/maps/search/?api=1&query=Novotel+Bucharest+City+Centre+Calea+Victoriei+37B">📍 מפה</a></div></div><div class="emergency-card"><h3>✈️ טיסות</h3><div class="flight-row"><b>הלוך · LY9491</b><br>TLV → OTP · 19.9.2026 · 00:20 → 03:05</div><div class="flight-row"><b>חזור · LY574</b><br>OTP → TLV · 30.9.2026 · 10:25 → 12:55</div></div><div class="emergency-card"><h3>🛡️ ביטוח נסיעות</h3><div class="controls" style="grid-template-columns:1fr"><label class="field"><span>חברת ביטוח</span><input id="insCompany" value="${esc(v.company||'')}" placeholder="למשל PassportCard"></label><label class="field"><span>מספר פוליסה</span><input id="insPolicy" value="${esc(v.policy||'')}" placeholder="מספר פוליסה"></label><label class="field"><span>טלפון חירום של הביטוח</span><input id="insPhone" class="ltr" value="${esc(v.phone||'')}" placeholder="+972..."></label></div><div class="emergency-actions"><button id="saveInsurance" type="button">שמור פרטי ביטוח</button><a id="callInsurance" href="#">📞 התקשר לביטוח</a></div><span id="insStatus" class="muted"></span></div></div><div class="warn" style="margin-top:14px">מומלץ לצלם מראש דרכונים, פוליסת ביטוח, אישורי מלון, voucher של הרכב וכרטיסי טיסה ולשמור גם אופליין.</div>`;main.appendChild(s);document.getElementById('saveInsurance').onclick=()=>{saveInsurance();updateCall()};['insPhone'].forEach(id=>document.getElementById(id)?.addEventListener('input',updateCall));updateCall()}
function updateCall(){const a=document.getElementById('callInsurance'),p=document.getElementById('insPhone')?.value.trim();if(!a)return;a.href=p?'tel:'+p:'#';a.style.opacity=p?'1':'.5';a.onclick=p?null:e=>e.preventDefault()}
function init(){navBtn();build()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();