(()=>{
'use strict';
const ENDPOINT_KEY='romania-sync-endpoint';
const DEVICE_KEY='romania-sync-device';
const MEMBER_KEY='romania-sync-member';
const MIGRATED_KEY='romania-sync-migrated-v1';
const LAST_SYNC_KEY='romania-last-sync';
const STATUS_TEXT_KEY='romania-sync-status-text';
const STATUS_CLASS_KEY='romania-sync-status-class';
const TODO_DELETED_KEY='romania-todo-deleted-v1';
const TRIP_TZ='Europe/Bucharest';
const device=(()=>{let d=localStorage.getItem(DEVICE_KEY);if(!d){d='dev-'+crypto.randomUUID();localStorage.setItem(DEVICE_KEY,d)}return d})();
function endpoint(){return (localStorage.getItem(ENDPOINT_KEY)||'').trim()}
function member(){return (localStorage.getItem(MEMBER_KEY)||'').trim()||'Family'}
function setStatus(text,cls=''){localStorage.setItem(STATUS_TEXT_KEY,text);localStorage.setItem(STATUS_CLASS_KEY,cls);const el=document.getElementById('settingsSyncStatus');if(el){el.textContent=text;el.dataset.state=cls}window.dispatchEvent(new CustomEvent('romania-sync-status',{detail:{text,cls}}))}
function safeJson(key,def){try{return JSON.parse(localStorage.getItem(key)||'null')??def}catch(e){return def}}
function deletedTodoIds(){return new Set((safeJson(TODO_DELETED_KEY,[])||[]).map(String))}
function normalizeDate(v){const s=String(v??'').trim().replace(/^d:/,'').replace(/^'/,'');if(!s)return '';if(/^\d{4}-\d{2}-\d{2}$/.test(s))return s;if(/^\d{4}-\d{2}-\d{2}T/.test(s)){const d=new Date(s);if(!Number.isNaN(d.getTime()))try{const parts=new Intl.DateTimeFormat('en-CA',{timeZone:TRIP_TZ,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(d);const p=Object.fromEntries(parts.map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}`}catch(e){}}const m=s.match(/(\d{4})[-\/.](\d{1,2})[-\/.](\d{1,2})/);return m?`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`:s.slice(0,10)}
function normalizeTime(v){const s=String(v??'').trim().replace(/^t:/,'').replace(/^'/,'');const m=s.match(/^(\d{1,2}):(\d{2})/);if(m)return `${m[1].padStart(2,'0')}:${m[2]}`;if(/^\d{4}-\d{2}-\d{2}T/.test(s)){const d=new Date(s);if(!Number.isNaN(d.getTime()))try{return new Intl.DateTimeFormat('en-GB',{timeZone:TRIP_TZ,hour:'2-digit',minute:'2-digit',hour12:false}).format(d)}catch(e){}}return s}
function localPayload(){const expenses=safeJson('romania-manual-expenses-v2',safeJson('romania-manual-expenses',[]));const deleted=deletedTodoIds();const todo=(safeJson('romania-todo-v1',[])||[]).filter(x=>!deleted.has(String(x.id)));const car=safeJson('romania-rental-car-details',{});const itinerary=safeJson('romania-itinerary-v2',[]);const fuel={type:localStorage.getItem('fuelType')||'',consumption:localStorage.getItem('fuelConsumption')||'',price:localStorage.getItem('fuelPrice')||''};const carRows=Object.entries(car||{}).map(([key,value])=>({key,value,updatedBy:member(),updatedAt:new Date().toISOString()}));Object.entries(fuel).forEach(([key,value])=>{if(value)carRows.push({key:'fuel_'+key,value,updatedBy:member(),updatedAt:new Date().toISOString()})});const expRows=(Array.isArray(expenses)?expenses:[]).map(x=>({id:String(x.id||crypto.randomUUID()),createdAt:x.createdAt||new Date().toISOString(),amount:Number(x.amount)||0,currency:x.currency||'ILS',description:x.description||'',category:x.category||'',paidBy:x.paidBy||member(),status:x.status||'committed',updatedBy:member(),updatedAt:new Date().toISOString()}));const todoRows=(Array.isArray(todo)?todo:[]).map(x=>({id:String(x.id||crypto.randomUUID()),date:'d:'+normalizeDate(x.date),time:'t:'+normalizeTime(x.time),text:x.text||'',category:x.cat||x.category||'',done:!!x.done,reminderMinutes:x.reminderMinutes||'',custom:!!x.custom,updatedBy:member(),updatedAt:new Date().toISOString()}));const itineraryRows=[];if(Array.isArray(itinerary))itinerary.forEach((day,di)=>(day?.s||[]).forEach((s,si)=>itineraryRows.push({id:`${di}-${si}-${String(s[0]).slice(0,40)}`,date:`2026-09-${String(23+di).padStart(2,'0')}`,time:s[3]||'',name:s[0]||'',description:s[4]||'',lat:s[1]||'',lng:s[2]||'',status:'planned',selected:true,updatedBy:member(),updatedAt:new Date().toISOString()})));return{Expenses:expRows,Todo:todoRows,Car:carRows,Itinerary:itineraryRows,Votes:[],Family:[],Settings:[]}}
async function api(body){const url=endpoint();if(!url)throw new Error('NO_ENDPOINT');const r=await fetch(url,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body),cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);return await r.json()}
async function getSnapshot(){const url=endpoint();if(!url)throw new Error('NO_ENDPOINT');const r=await fetch(url+'?action=snapshot&t='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);return await r.json()}
function applySnapshot(data){if(!data)return;if(Array.isArray(data.Expenses))localStorage.setItem('romania-manual-expenses-v2',JSON.stringify(data.Expenses.map(x=>({id:String(x.id),createdAt:x.createdAt,amount:Number(x.amount),currency:x.currency,description:x.description,category:x.category,paidBy:x.paidBy,status:x.status}))));if(Array.isArray(data.Todo)){const deleted=deletedTodoIds();localStorage.setItem('romania-todo-v1',JSON.stringify(data.Todo.filter(x=>!deleted.has(String(x.id))).map(x=>({id:String(x.id),date:normalizeDate(x.date),time:normalizeTime(x.time),text:x.text,cat:x.category,done:String(x.done)==='true'||x.done===true,reminderMinutes:x.reminderMinutes,custom:String(x.custom)==='true'||x.custom===true}))))}if(Array.isArray(data.Car)){const obj={};data.Car.forEach(x=>obj[x.key]=x.value);localStorage.setItem('romania-rental-car-details',JSON.stringify({model:obj.model||'Volkswagen Tiguan Automatic או דומה',engine:obj.engine||'לא ידוע עדיין',fuel:obj.fuel||'petrol'}));if(obj.fuel_type)localStorage.setItem('fuelType',obj.fuel_type);if(obj.fuel_consumption)localStorage.setItem('fuelConsumption',obj.fuel_consumption);if(obj.fuel_price)localStorage.setItem('fuelPrice',obj.fuel_price)}try{window.RomaniaSummary?.render?.();window.RomaniaTodo?.render?.();window.renderHome?.()}catch(e){}}
async function migrateAndSync(){if(!endpoint()){setStatus('🟡 אופליין · הנתונים נשמרים במכשיר','offline');return}setStatus('🔄 מסנכרן…','syncing');try{const first=localStorage.getItem(MIGRATED_KEY)!=='1';if(first){const res=await api({action:'sync',device,member:member(),data:localPayload()});if(!res.ok)throw new Error(res.error||'sync failed');localStorage.setItem(MIGRATED_KEY,'1');applySnapshot(res.data)}else{const snap=await getSnapshot();if(!snap.ok)throw new Error(snap.error||'snapshot failed');applySnapshot(snap.data)}localStorage.setItem(LAST_SYNC_KEY,new Date().toISOString());setStatus('🟢 מסונכרן','ok')}catch(e){setStatus('🟡 אופליין · הנתונים נשמרים במכשיר','offline')}}
async function pushNow(){if(!endpoint())return migrateAndSync();setStatus('🔄 מסנכרן…','syncing');try{const res=await api({action:'sync',device,member:member(),data:localPayload()});if(!res.ok)throw new Error(res.error||'sync failed');localStorage.setItem(MIGRATED_KEY,'1');applySnapshot(res.data);localStorage.setItem(LAST_SYNC_KEY,new Date().toISOString());setStatus('🟢 מסונכרן','ok')}catch(e){setStatus('🟡 אופליין · הנתונים נשמרים במכשיר','offline')}}
async function deleteTodo(id){id=String(id||'');if(!id)return;const del=deletedTodoIds();del.add(id);localStorage.setItem(TODO_DELETED_KEY,JSON.stringify([...del]));localStorage.setItem('romania-todo-v1',JSON.stringify((safeJson('romania-todo-v1',[])||[]).filter(x=>String(x.id)!==id)));if(!endpoint())return;setStatus('🔄 מסנכרן…','syncing');try{const res=await api({action:'delete',sheet:'Todo',ids:[id],keyField:'id'});if(!res.ok)throw new Error(res.error||'delete failed');localStorage.setItem(LAST_SYNC_KEY,new Date().toISOString());setStatus('🟢 מסונכרן','ok')}catch(e){setStatus('🟡 אופליין · הנתונים נשמרים במכשיר','offline')}}
function build(){document.getElementById('familySyncBar')?.remove();document.getElementById('connectionMini')?.remove()}
function watch(){window.addEventListener('online',migrateAndSync);window.addEventListener('offline',()=>setStatus('🟡 אופליין · הנתונים נשמרים במכשיר','offline'));window.addEventListener('storage',e=>{if(e.key&&e.key.startsWith('romania-'))setTimeout(pushNow,400)});setInterval(()=>{if(document.visibilityState==='visible'&&endpoint())migrateAndSync()},60000)}
function init(){build();setTimeout(migrateAndSync,100);watch()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
window.RomaniaFamilySync={sync:pushNow,deleteTodo,setEndpoint:u=>{localStorage.setItem(ENDPOINT_KEY,u);localStorage.removeItem(MIGRATED_KEY);return migrateAndSync()},endpoint};
})();