(()=>{
'use strict';
let calcNodes=null;
const TODO_KEY='romania-todo-v1';
function injectStyle(){if(document.getElementById('homeToolsStyle'))return;const s=document.createElement('style');s.id='homeToolsStyle';s.textContent=`
#homeTools{margin-top:18px}#homeCalculatorHost{margin-top:10px}#homeCalculatorHost>.card{margin:0!important}#homeCalculatorHost>h1{display:none!important}#page-calculator{display:none!important}
.dashboard-todo-preview{display:grid;gap:8px}.dashboard-todo-item{display:grid;grid-template-columns:auto 1fr;gap:9px;align-items:start;padding:9px 10px;border:1px solid var(--line,#DED5C9);border-radius:12px;background:var(--soft,#F1E8DE)}.dashboard-todo-check{font-size:1.05rem;line-height:1.2}.dashboard-todo-text{font-weight:800;line-height:1.3}.dashboard-todo-meta{font-size:.76rem;color:var(--muted,#6F716B);margin-top:2px}.dashboard-todo-more{width:100%;margin-top:4px;border:0;border-radius:10px;padding:9px 10px;background:var(--p,#31473A);color:#fff;font-weight:800;cursor:pointer}
body{padding-bottom:104px!important}#mobileDock,#moreSheet{display:none!important}
html>#quickFloat{position:fixed!important;display:block!important;left:12px!important;right:12px!important;top:auto!important;bottom:max(6px,env(safe-area-inset-bottom,0px))!important;margin:0 auto!important;z-index:2147483000!important;width:auto!important;max-width:980px!important;padding:7px!important;border:1px solid var(--line,#DED5C9)!important;border-radius:18px!important;background:rgba(255,252,247,.97)!important;box-shadow:0 12px 34px #0004!important;backdrop-filter:blur(16px)!important;-webkit-backdrop-filter:blur(16px)!important;transform:none!important;-webkit-transform:none!important;translate:none!important;overflow:visible!important}
#quickFloat .qf-main{display:grid!important;grid-template-columns:repeat(6,minmax(0,1fr))!important;gap:6px!important;direction:rtl!important}
#quickFloat button{min-width:0!important;min-height:58px!important;padding:6px 4px!important;border-radius:12px!important;font-size:.76rem!important;font-weight:850!important;background:var(--soft,#F1E8DE)!important;color:var(--text,#1F2A24)!important;border:1px solid var(--line,#DED5C9)!important;cursor:pointer!important;white-space:nowrap!important}
#quickFloat button span{display:block!important;font-size:1.3rem!important;margin-bottom:2px!important;line-height:1.1!important}
#quickFloat .qf-more{display:none;position:absolute!important;left:7px!important;right:7px!important;bottom:calc(100% + 8px)!important;padding:8px!important;border:1px solid var(--line,#DED5C9)!important;border-radius:16px!important;background:rgba(255,252,247,.98)!important;box-shadow:0 12px 32px #0005!important;grid-template-columns:repeat(5,minmax(0,1fr))!important;gap:6px!important;direction:rtl!important;z-index:2147483001!important;overflow:visible!important}
#quickFloat.open .qf-more{display:grid!important}:root[data-theme="dark"] #quickFloat,:root[data-theme="dark"] #quickFloat .qf-more{background:rgba(27,33,29,.98)!important}
@media(max-width:700px){body{padding-bottom:94px!important}html>#quickFloat{left:7px!important;right:7px!important;bottom:max(4px,env(safe-area-inset-bottom,0px))!important;padding:5px!important;border-radius:16px!important}#quickFloat .qf-main{gap:4px!important}#quickFloat button{min-height:54px!important;font-size:.66rem!important;padding:5px 1px!important;border-radius:10px!important}#quickFloat button span{font-size:1.15rem!important}#quickFloat .qf-more{grid-template-columns:repeat(5,minmax(0,1fr))!important;left:5px!important;right:5px!important;gap:4px!important;padding:6px!important}#quickFloat .qf-more button{font-size:.62rem!important}}
@media(max-width:430px){#quickFloat button{font-size:.61rem!important}#quickFloat button span{font-size:1.08rem!important}}
`;document.head.appendChild(s)}
function navTo(page){const b=document.querySelector(`header .nav button[data-page="${page}"]`);if(b){b.click();return}document.querySelectorAll('.page').forEach(p=>p.classList.remove('on'));document.getElementById('page-'+page)?.classList.add('on');try{if(page==='home'&&typeof renderHome==='function')renderHome();if(page==='summary')window.RomaniaSummary?.render?.();if(page==='todo')window.RomaniaTodo?.render?.();if(page==='trip'&&window.map)setTimeout(()=>window.map.invalidateSize?.(),80)}catch(e){}window.scrollTo({top:0,behavior:'smooth'})}
function openGoogleTranslate(){const ua=navigator.userAgent||'',play='https://play.google.com/store/apps/details?id=com.google.android.apps.translate',appStore='https://apps.apple.com/app/google-translate/id414706506';if(/Android/i.test(ua)){location.href='intent://translate.google.com/#Intent;scheme=https;package=com.google.android.apps.translate;S.browser_fallback_url='+encodeURIComponent(play)+';end';return}if(/iPhone|iPad|iPod/i.test(ua)){const started=Date.now();location.href='googletranslate://';setTimeout(()=>{if(Date.now()-started<2200)location.href=appStore},1200);return}window.open('https://translate.google.com/?sl=auto&tl=ro&op=translate','_blank','noopener')}
function removeTopMenuItems(){document.querySelectorAll('header .nav button').forEach(b=>b.style.display='none');document.querySelectorAll('.page').forEach(p=>{if(/translate|translation/i.test(p.id||''))p.remove()})}
function pinFloatingMenu(){const f=document.getElementById('quickFloat');if(!f)return;if(f.parentNode!==document.documentElement)document.documentElement.appendChild(f);f.style.position='fixed';f.style.top='auto';f.style.bottom='max(6px, env(safe-area-inset-bottom, 0px))';f.style.left=innerWidth<=700?'7px':'12px';f.style.right=innerWidth<=700?'7px':'12px';f.style.transform='none';f.style.zIndex='2147483000';f.style.overflow='visible'}
function bindFloatingMenu(f){if(f.dataset.bound==='1')return;f.dataset.bound='1';f.addEventListener('click',e=>{const more=e.target.closest('[data-qf-more]');if(more){e.preventDefault();e.stopPropagation();f.classList.toggle('open');return}const page=e.target.closest('[data-qf-page]');if(page){e.preventDefault();f.classList.remove('open');navTo(page.dataset.qfPage);return}const tr=e.target.closest('[data-qf-translate]');if(tr){e.preventDefault();f.classList.remove('open');openGoogleTranslate()}});document.addEventListener('click',e=>{if(!f.contains(e.target))f.classList.remove('open')})}
function buildFloatingMenu(){let f=document.getElementById('quickFloat');if(!f){f=document.createElement('nav');f.id='quickFloat';f.setAttribute('aria-label','תפריט מהיר');f.innerHTML=`<div class="qf-main"><button type="button" data-qf-page="home"><span>🏠</span>ראשי</button><button type="button" data-qf-page="checkin"><span>✈️</span>טיסות</button><button type="button" data-qf-page="hotels"><span>🏨</span>מלונות</button><button type="button" data-qf-page="car"><span>🚙</span>רכב</button><button type="button" data-qf-page="trip"><span>🧭</span>מסלול</button><button type="button" data-qf-more aria-expanded="false"><span>•••</span>עוד</button></div><div class="qf-more"><button type="button" data-qf-page="emergency"><span>🆘</span>חשוב</button><button type="button" data-qf-translate><span>🌐</span>תרגום</button><button type="button" data-qf-page="todo"><span>✅</span>To Do</button><button type="button" data-qf-page="summary"><span>💰</span>סיכומים</button><button type="button" data-qf-page="settings"><span>⚙️</span>הגדרות</button></div>`;document.documentElement.appendChild(f)}bindFloatingMenu(f);pinFloatingMenu()}
function loadTodos(){try{const a=JSON.parse(localStorage.getItem(TODO_KEY)||'[]');return Array.isArray(a)?a:[]}catch(e){return[]}}
function todoPreviewHtml(){const list=loadTodos().filter(x=>!x.done).sort((a,b)=>`${a.date||''} ${a.time||''}`.localeCompare(`${b.date||''} ${b.time||''}`)).slice(0,4);if(!list.length)return '<div class="dash-empty">אין כרגע משימות פתוחות.</div><button class="dashboard-todo-more" type="button" data-open-todo>פתח To Do</button>';return `<div class="dashboard-todo-preview">${list.map(x=>`<div class="dashboard-todo-item"><div class="dashboard-todo-check">☐</div><div><div class="dashboard-todo-text">${String(x.text||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}</div><div class="dashboard-todo-meta">${x.date||''}${x.time?' · '+x.time:''}${x.cat?' · '+x.cat:''}</div></div></div>`).join('')}</div><button class="dashboard-todo-more" type="button" data-open-todo>לכל המשימות</button>`}
function replaceOldQuickWithTodo(){const grid=document.querySelector('#page-home .dash-actions');if(!grid)return;const card=grid.closest('.dash-card');if(!card||card.dataset.todoPreview==='1')return;card.dataset.todoPreview='1';card.innerHTML=`<h2>✅ משימות קרובות</h2>${todoPreviewHtml()}`;card.querySelector('[data-open-todo]')?.addEventListener('click',()=>navTo('todo'))}
function captureCalculator(){if(calcNodes?.length)return true;const calc=document.getElementById('page-calculator');if(!calc)return false;calcNodes=[...calc.childNodes];return calcNodes.length>0}
function mountCalculator(){const home=document.getElementById('page-home');if(!home||!captureCalculator())return;let box=document.getElementById('homeTools');if(!box){box=document.createElement('section');box.id='homeTools';box.className='dash-card';box.innerHTML='<h2>🧮 מחשבון מטבע</h2><div id="homeCalculatorHost"></div>';const dash=document.getElementById('realDashboard');(dash||home).appendChild(box)}const host=document.getElementById('homeCalculatorHost');if(!host)return;calcNodes.forEach(n=>{if(n.parentNode!==host)host.appendChild(n)});const calc=document.getElementById('page-calculator');if(calc)calc.style.display='none'}
function refresh(){injectStyle();removeTopMenuItems();buildFloatingMenu();replaceOldQuickWithTodo();mountCalculator();pinFloatingMenu()}
function init(){captureCalculator();refresh();[300,800,1500,2600].forEach(t=>setTimeout(refresh,t));window.addEventListener('resize',()=>setTimeout(refresh,30));window.addEventListener('orientationchange',()=>setTimeout(refresh,100));window.visualViewport?.addEventListener('resize',()=>setTimeout(pinFloatingMenu,0));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')setTimeout(refresh,30)});window.addEventListener('pageshow',()=>setTimeout(refresh,20));window.addEventListener('storage',e=>{if(e.key===TODO_KEY)setTimeout(refresh,50)});new MutationObserver(()=>{if(document.getElementById('page-home'))setTimeout(refresh,30)}).observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();