(()=>{
'use strict';
let calcNodes=null;
const TODO_KEY='romania-todo-v1';
const QUICK_ORDER=['trip','hotels','flights','car','emergency','todo','translate','summary','settings'];
function injectStyle(){if(document.getElementById('homeToolsStyle'))return;const s=document.createElement('style');s.id='homeToolsStyle';s.textContent=`
#homeTools{margin-top:18px}#homeCalculatorHost{margin-top:10px}.home-quick-grid{grid-template-columns:repeat(9,minmax(0,1fr))!important}.home-quick[data-quick-translate]{border-color:var(--trans-gold,#B68A4C)!important}.home-quick[data-quick-translate] span{font-size:1.25rem}
#homeCalculatorHost>.card{margin:0!important}#homeCalculatorHost>h1{display:none!important}#page-calculator{display:none!important}
#quickFloat{display:none}
.dashboard-todo-preview{display:grid;gap:8px}.dashboard-todo-item{display:grid;grid-template-columns:auto 1fr;gap:9px;align-items:start;padding:9px 10px;border:1px solid var(--line,#DED5C9);border-radius:12px;background:var(--soft,#F1E8DE)}.dashboard-todo-check{font-size:1.05rem;line-height:1.2}.dashboard-todo-text{font-weight:800;line-height:1.3}.dashboard-todo-meta{font-size:.76rem;color:var(--muted,#6F716B);margin-top:2px}.dashboard-todo-more{width:100%;margin-top:4px;border:0;border-radius:10px;padding:9px 10px;background:var(--p,#31473A);color:#fff;font-weight:800;cursor:pointer}
@media(min-width:851px){body{padding-bottom:92px!important}#quickFloat{position:fixed;display:block;left:50%;transform:translateX(-50%);bottom:12px;z-index:3950;width:min(1120px,calc(100vw - 28px));padding:7px 9px;border:1px solid var(--line,#DED5C9);border-radius:18px;background:rgba(255,252,247,.94);box-shadow:0 12px 34px #0003;backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px)}#quickFloat .dash-actions{display:grid!important;grid-template-columns:repeat(9,minmax(0,1fr))!important;gap:6px!important}#quickFloat .dash-actions button{min-height:58px!important;padding:7px 4px!important;border-radius:12px!important;font-size:.76rem!important;background:var(--soft,#F1E8DE)!important;color:var(--text,#1F2A24)!important;border:1px solid var(--line,#DED5C9)!important}#quickFloat .dash-actions button span{display:block!important;font-size:1.35rem!important;margin-bottom:2px!important}:root[data-theme="dark"] #quickFloat{background:rgba(27,33,29,.94)!important}}
@media(max-width:850px){.home-quick-grid{grid-template-columns:repeat(3,minmax(0,1fr))!important}#homeTools .calc-grid{grid-template-columns:1fr!important}#homeTools .swap{justify-self:center;transform:rotate(90deg)}#homeTools .rate-cards{grid-template-columns:repeat(2,minmax(0,1fr))!important}}
@media(max-width:520px){.home-quick-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}#homeTools .rate-cards{grid-template-columns:1fr!important}}
`;document.head.appendChild(s)}
function navTo(page){const b=document.querySelector(`header .nav button[data-page="${page}"]`);if(b){b.click();return}document.querySelectorAll('.page').forEach(p=>p.classList.remove('on'));document.getElementById('page-'+page)?.classList.add('on');window.scrollTo({top:0,behavior:'smooth'})}
function removeFromMenus(){document.querySelectorAll('header .nav button').forEach(b=>{const t=(b.textContent||'').trim(),p=b.dataset.page||'';if(['calculator','checkin','todo','trip','hotels','car','emergency','summary','settings'].includes(p)||/תרגום/.test(t))b.remove()});document.querySelectorAll('#moreSheet button').forEach(b=>{const t=(b.textContent||'').trim(),p=b.dataset.go||'';if(['calculator','checkin','todo'].includes(p)||/תרגום/.test(t))b.remove()});document.querySelectorAll('.page').forEach(p=>{if(/translate|translation/i.test(p.id||''))p.remove()})}
function openGoogleTranslate(){const ua=navigator.userAgent||'',play='https://play.google.com/store/apps/details?id=com.google.android.apps.translate',appStore='https://apps.apple.com/app/google-translate/id414706506';if(/Android/i.test(ua)){location.href='intent://translate.google.com/#Intent;scheme=https;package=com.google.android.apps.translate;S.browser_fallback_url='+encodeURIComponent(play)+';end';return}if(/iPhone|iPad|iPod/i.test(ua)){const started=Date.now();location.href='googletranslate://';setTimeout(()=>{if(Date.now()-started<2200)location.href=appStore},1200);return}window.open('https://translate.google.com/?sl=auto&tl=ro&op=translate','_blank','noopener')}
function quickGrid(){return document.querySelector('#quickFloat .dash-actions')||document.querySelector('#homeSmartPanel .home-quick-grid')||document.querySelector('#page-home .home-quick-grid')||document.querySelector('#page-home .dash-actions')}
function addQuick(key,icon,label,handler){const grid=quickGrid();if(!grid||grid.querySelector(`[data-quick-${key}]`))return;const b=document.createElement('button');if(!grid.classList.contains('dash-actions'))b.className='home-quick';b.type='button';b.setAttribute(`data-quick-${key}`,'1');b.dataset.quickKey=key;b.innerHTML=`<span>${icon}</span>${label}`;b.onclick=handler;grid.appendChild(b)}
function markExistingQuick(){const grid=quickGrid();if(!grid)return;const map={trip:'trip',hotels:'hotels',car:'car',emergency:'emergency'};grid.querySelectorAll('button[data-go]').forEach(b=>{const k=map[b.dataset.go];if(k&&!b.dataset.quickKey)b.dataset.quickKey=k})}
function orderQuick(){const grid=quickGrid();if(!grid)return;markExistingQuick();const nodes=[...grid.querySelectorAll('button')];nodes.sort((a,b)=>{const ak=a.dataset.quickKey||Object.keys(a.dataset).find(k=>k.startsWith('quick'))?.replace(/^quick/,'').toLowerCase()||'',bk=b.dataset.quickKey||Object.keys(b.dataset).find(k=>k.startsWith('quick'))?.replace(/^quick/,'').toLowerCase()||'';const ai=QUICK_ORDER.indexOf(ak),bi=QUICK_ORDER.indexOf(bk);return(ai<0?999:ai)-(bi<0?999:bi)}).forEach(n=>grid.appendChild(n))}
function addQuickActions(){addQuick('flights','✈️','טיסות',()=>navTo('checkin'));addQuick('todo','✅','To Do',()=>navTo('todo'));addQuick('translate','🌐','תרגום',openGoogleTranslate);addQuick('summary','💰','סיכומים',()=>navTo('summary'));addQuick('settings','⚙️','הגדרות',()=>navTo('settings'));orderQuick()}
function loadTodos(){try{const a=JSON.parse(localStorage.getItem(TODO_KEY)||'[]');return Array.isArray(a)?a:[]}catch(e){return[]}}
function todoPreviewHtml(){const list=loadTodos().filter(x=>!x.done).sort((a,b)=>`${a.date||''} ${a.time||''}`.localeCompare(`${b.date||''} ${b.time||''}`)).slice(0,4);if(!list.length)return '<div class="dash-empty">אין כרגע משימות פתוחות.</div><button class="dashboard-todo-more" type="button" data-open-todo>פתח To Do</button>';return `<div class="dashboard-todo-preview">${list.map(x=>`<div class="dashboard-todo-item"><div class="dashboard-todo-check">☐</div><div><div class="dashboard-todo-text">${String(x.text||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}</div><div class="dashboard-todo-meta">${x.date||''}${x.time?' · '+x.time:''}${x.cat?' · '+x.cat:''}</div></div></div>`).join('')}</div><button class="dashboard-todo-more" type="button" data-open-todo>לכל המשימות</button>`}
function floatDesktopQuick(){if(innerWidth<=850){document.getElementById('quickFloat')?.remove();return}const grid=document.querySelector('#page-home .dash-actions');if(!grid)return;const card=grid.closest('.dash-card');let float=document.getElementById('quickFloat');if(!float){float=document.createElement('div');float.id='quickFloat';document.body.appendChild(float)}float.replaceChildren(grid);if(card){card.innerHTML=`<h2>✅ משימות קרובות</h2>${todoPreviewHtml()}`;card.querySelector('[data-open-todo]')?.addEventListener('click',()=>navTo('todo'))}setTimeout(()=>{addQuickActions();orderQuick()},0)}
function captureCalculator(){if(calcNodes?.length)return true;const calc=document.getElementById('page-calculator');if(!calc)return false;calcNodes=[...calc.childNodes];return calcNodes.length>0}
function mountCalculator(){const home=document.getElementById('page-home');if(!home||!captureCalculator())return;let box=document.getElementById('homeTools');if(!box){box=document.createElement('section');box.id='homeTools';box.className='dash-card';box.innerHTML='<h2>🧮 מחשבון מטבע</h2><div id="homeCalculatorHost"></div>';const dash=document.getElementById('realDashboard');(dash||home).appendChild(box)}const host=document.getElementById('homeCalculatorHost');if(!host)return;calcNodes.forEach(n=>{if(n.parentNode!==host)host.appendChild(n)});const calc=document.getElementById('page-calculator');if(calc)calc.style.display='none'}
function refresh(){injectStyle();removeFromMenus();mountCalculator();addQuickActions();floatDesktopQuick();setTimeout(()=>{addQuickActions();orderQuick()},20)}
function init(){captureCalculator();refresh();[300,800,1500,2600].forEach(t=>setTimeout(refresh,t));window.addEventListener('resize',()=>setTimeout(refresh,80));window.addEventListener('storage',e=>{if(e.key===TODO_KEY)setTimeout(refresh,50)});new MutationObserver(()=>{if(document.getElementById('page-home'))setTimeout(refresh,30)}).observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();