(()=>{
const TRIP_START=new Date('2026-09-23T00:00:00+03:00');
const TRIP_END=new Date('2026-09-30T23:59:59+03:00');
const STORAGE_KEY='romania-itinerary-v2';
const style=document.createElement('style');
style.textContent=`
.home-hero{background:linear-gradient(135deg,#0d6f88,#1496b5);color:#fff;border-radius:20px;padding:22px;margin-bottom:16px}.home-hero h1{margin:0 0 6px}.home-grid{display:grid;grid-template-columns:1.3fr .7fr;gap:14px}.home-list{display:grid;gap:9px}.home-item{background:#f8fafb;border:1px solid var(--line,#d8e3e7);border-radius:12px;padding:11px}.home-item b{display:block}.rules{display:grid;gap:8px}.rule{background:#fff8db;border-right:4px solid #d7a31c;border-radius:10px;padding:10px}.route-editor{margin-top:18px}.edit-day{background:#fff;border:1px solid var(--line,#d8e3e7);border-radius:16px;padding:14px;margin-bottom:12px}.edit-day h3{margin:0 0 10px}.attraction-row{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center;padding:10px;border-top:1px solid #e8eef0}.attraction-row:first-of-type{border-top:0}.move-controls{display:flex;gap:6px;align-items:center}.move-controls select{padding:7px;border:1px solid #cfdde2;border-radius:8px;background:#fff}.move-controls button{border:0;background:#0d6f88;color:#fff;border-radius:8px;padding:7px 9px;cursor:pointer}.fixed-tag{font-size:.78rem;background:#eef6f8;border-radius:999px;padding:4px 7px;color:#52666f}.edit-note{font-size:.84rem;color:#667983}.home-kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin-top:12px}.home-kpi{background:#ffffff22;border:1px solid #ffffff55;border-radius:12px;padding:10px}.home-kpi b{display:block;font-size:1.2rem}.today-badge{display:inline-block;background:#fff;color:#0d6f88;border-radius:999px;padding:5px 9px;font-weight:800;margin-bottom:8px}@media(max-width:850px){.home-grid,.home-kpis{grid-template-columns:1fr}.attraction-row{grid-template-columns:1fr}.move-controls{flex-wrap:wrap}.move-controls select{flex:1;min-width:150px}}
`;
document.head.appendChild(style);

function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function cloneDays(){try{return JSON.parse(JSON.stringify(D));}catch(e){return [];}}
function loadCustom(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');}catch(e){return null;}}
function saveCustom(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(D));}catch(e){}}
function applyCustom(){const saved=loadCustom();if(!saved||!Array.isArray(saved)||!Array.isArray(D))return;D.splice(0,D.length,...saved);}
function dayDate(i){return new Date(2026,8,23+i);}
function dayLabel(i){const d=dayDate(i);return `${d.getDate()}.9`}
function currentTripIndex(){const now=new Date();const local=new Date(now.toLocaleString('en-US',{timeZone:'Europe/Bucharest'}));const y=local.getFullYear(),m=local.getMonth(),d=local.getDate();if(y===2026&&m===8&&d>=23&&d<=30)return d-23;return -1;}
function nextTripIndex(){const now=new Date();if(now<TRIP_START)return 0;if(now>TRIP_END)return D.length-1;return currentTripIndex();}
function daysUntil(){const ms=TRIP_START-Date.now();return Math.max(0,Math.ceil(ms/86400000));}
function isFixedStop(name,desc=''){const s=(name+' '+desc).toLowerCase();return /(hotel|swissôtel|swissotel|novotel|otp|airport|שדה|מלון|צ׳ק|צ'ק|חזרה למלון|יציאה)/i.test(s);}
function navTo(page){const btn=document.querySelector(`.nav button[data-page="${page}"]`);if(btn)btn.click();else{document.querySelectorAll('.page').forEach(p=>p.classList.remove('on'));const el=document.getElementById('page-'+page);if(el)el.classList.add('on');}}

function addHomeNav(){const nav=document.querySelector('.nav');if(!nav||nav.querySelector('[data-page="home"]'))return;const b=document.createElement('button');b.dataset.page='home';b.textContent='🏠 ראשי';nav.insertBefore(b,nav.firstChild);b.addEventListener('click',()=>{document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('on',x===b));document.querySelectorAll('.page').forEach(p=>p.classList.remove('on'));document.getElementById('page-home')?.classList.add('on');renderHome();window.scrollTo({top:0,behavior:'smooth'});});}
function homeStatus(){const idx=currentTripIndex();if(idx>=0)return {title:`היום · ${dayLabel(idx)} · ${D[idx]?.n||''}`,idx,badge:'היום בטיול'};if(Date.now()<TRIP_START)return {title:`הטיול מתחיל בעוד ${daysUntil()} ימים`,idx:0,badge:'לפני הטיול'};return {title:'הטיול הסתיים',idx:D.length-1,badge:'סיכום'};}
function buildHome(){if(document.getElementById('page-home'))return;const main=document.querySelector('main.wrap');if(!main)return;const sec=document.createElement('section');sec.id='page-home';sec.className='page';sec.innerHTML=`<div class="home-hero"><span class="today-badge" id="homeBadge"></span><h1 id="homeTitle">רומניה 2026</h1><div id="homeSub"></div><div class="home-kpis"><div class="home-kpi"><span>מלונות</span><b>7 לילות</b></div><div class="home-kpi"><span>רכב</span><b>Tiguan Auto</b></div><div class="home-kpi"><span>מסלול</span><b>23–30.9</b></div></div></div><div class="home-grid"><div><div class="card"><h2>📍 מה בתוכנית</h2><div id="homeToday" class="home-list"></div><button class="btn" id="openTodayRoute">פתח מסלול וערוך</button></div><div class="card" style="margin-top:14px"><h2>🗓️ סיכום המסלולים</h2><div id="homeDays" class="home-list"></div></div></div><div><div class="card"><h2>✅ כללים חשובים</h2><div class="rules"><div class="rule">לא לתדלק בתחנת <b>Lukoil</b>.</div><div class="rule">בבוקרשט: אפליקציית חניה <b>Parking Bucharest</b>.</div><div class="rule">לפני Transfăgărășan לבדוק פתיחת DN7C ומזג אוויר 24–48 שעות מראש.</div><div class="rule">Therme: לשים לב לכללי גובה/אזורי ילדים.</div><div class="rule">Klass Wagen: להגיע לנקודת המפגש ולהזמין Shuttle; כרטיס Visa/MasterCard פיזי.</div></div></div><div class="card" style="margin-top:14px"><h2>⚡ קיצורים</h2><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn" data-home-go="hotels">🏨 מלונות</button><button class="btn" data-home-go="car">🚙 רכב</button><button class="btn" data-home-go="calculator">🧮 מחשבון</button><button class="btn" data-home-go="summary">💰 סיכומים</button></div></div></div></div>`;
main.insertBefore(sec,main.firstChild);
sec.querySelectorAll('[data-home-go]').forEach(b=>b.addEventListener('click',()=>navTo(b.dataset.homeGo)));
sec.querySelector('#openTodayRoute').addEventListener('click',()=>{const st=homeStatus();navTo('trip');setTimeout(()=>{try{show(st.idx)}catch(e){};document.querySelector('.route-editor')?.scrollIntoView({behavior:'smooth',block:'start'});},50);});
}
function renderHome(){buildHome();const s=homeStatus(),d=D[s.idx];document.getElementById('homeBadge').textContent=s.badge;document.getElementById('homeTitle').textContent=s.title;document.getElementById('homeSub').textContent=s.idx>=0&&d?`${d.s.length} תחנות מתוכננות · ניתן לשנות במסך מסלול`:'';const today=document.getElementById('homeToday');today.innerHTML=(d?.s||[]).map(x=>`<div class="home-item"><b>${esc(x[3])} · ${esc(x[0])}</b><span class="muted">${esc(x[4])}</span></div>`).join('')||'<div class="muted">אין תוכנית להיום.</div>';document.getElementById('homeDays').innerHTML=D.map((day,i)=>`<div class="home-item"><b>${dayLabel(i)} · ${esc(day.n)}</b><span class="muted">${day.s.filter(x=>!isFixedStop(x[0],x[4])).map(x=>esc(x[0])).join(' · ')||'נסיעות / מעבר'}</span></div>`).join('');}

function installRouteEditor(){const trip=document.getElementById('page-trip');if(!trip||trip.querySelector('.route-editor'))return;const h=document.createElement('div');h.className='route-editor';h.innerHTML=`<h2>✏️ עריכת מסלול ואטרקציות</h2><div class="card"><p>אפשר להעביר אטרקציה ליום אחר. השינויים נשמרים במכשיר ומשפיעים על הרשימה והמפה.</p><div id="routeEditorDays"></div><button class="btn" id="resetItinerary" style="background:#7a3e00">↩️ איפוס למסלול המקורי</button></div>`;trip.appendChild(h);h.querySelector('#resetItinerary').addEventListener('click',()=>{if(!confirm('לאפס את כל השינויים במסלול?'))return;localStorage.removeItem(STORAGE_KEY);location.reload();});renderRouteEditor();}
function renderRouteEditor(){const root=document.getElementById('routeEditorDays');if(!root)return;root.innerHTML=D.map((day,di)=>`<div class="edit-day"><h3>${dayLabel(di)} · ${esc(day.n)}</h3>${day.s.map((x,si)=>{const fixed=isFixedStop(x[0],x[4]);return `<div class="attraction-row"><div><b>${esc(x[3])} · ${esc(x[0])}</b><div class="edit-note">${esc(x[4])}</div></div>${fixed?'<span class="fixed-tag">תחנת מסלול קבועה</span>':`<div class="move-controls"><select data-move-select="${di}-${si}">${D.map((_,j)=>`<option value="${j}" ${j===di?'selected':''}>${dayLabel(j)}</option>`).join('')}</select><button data-move="${di}-${si}">העבר</button></div>`}</div>`}).join('')}</div>`).join('');root.querySelectorAll('[data-move]').forEach(btn=>btn.addEventListener('click',()=>{const [from,idx]=btn.dataset.move.split('-').map(Number);const sel=root.querySelector(`[data-move-select="${from}-${idx}"]`);const to=Number(sel.value);if(to===from)return;moveStop(from,idx,to);}));}
function moveStop(from,idx,to){if(!D[from]||!D[to]||!D[from].s[idx])return;const [stop]=D[from].s.splice(idx,1);D[to].s.push(stop);saveCustom();renderRouteEditor();try{show(to)}catch(e){};renderHome();}
function addMoveButtonsToStops(){const stops=document.getElementById('stops');if(!stops||stops.__observer)return;const obs=new MutationObserver(()=>{const idx=[...document.querySelectorAll('.tab')].findIndex(x=>x.classList.contains('on'));if(idx<0)return;[...stops.children].forEach((el,si)=>{const x=D[idx]?.s?.[si];if(!x||isFixedStop(x[0],x[4])||el.querySelector('.quick-move'))return;const wrap=document.createElement('div');wrap.className='quick-move move-controls';wrap.style.marginTop='7px';wrap.innerHTML=`<select>${D.map((_,j)=>`<option value="${j}" ${j===idx?'selected':''}>העבר ל-${dayLabel(j)}</option>`).join('')}</select><button>העבר</button>`;wrap.querySelector('button').addEventListener('click',()=>{const to=Number(wrap.querySelector('select').value);if(to!==idx)moveStop(idx,si,to);});el.appendChild(wrap);});});obs.observe(stops,{childList:true,subtree:false});stops.__observer=obs;setTimeout(()=>obs.takeRecords(),0);}

function patchExistingNav(){document.querySelectorAll('.nav button').forEach(b=>{if(b.__planner)return;b.__planner=true;b.addEventListener('click',()=>{if(b.dataset.page!=='home')setTimeout(()=>{if(b.dataset.page==='trip'){installRouteEditor();renderRouteEditor();}},0);});});}

function init(){if(typeof D==='undefined')return;applyCustom();addHomeNav();buildHome();patchExistingNav();installRouteEditor();addMoveButtonsToStops();renderHome();const homeBtn=document.querySelector('.nav button[data-page="home"]');if(homeBtn)homeBtn.click();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();