(()=>{
const TRIP_START=new Date('2026-09-23T00:00:00+03:00');
const TRIP_END=new Date('2026-09-30T23:59:59+03:00');
const STORAGE_KEY='romania-itinerary-v2';
const style=document.createElement('style');
style.textContent=`.home-hero{background:linear-gradient(135deg,#0d6f88,#1496b5);color:#fff;border-radius:20px;padding:22px;margin-bottom:16px}.home-hero h1{margin:0 0 6px}.home-grid{display:grid;grid-template-columns:1.3fr .7fr;gap:14px}.home-list{display:grid;gap:9px}.home-item{background:#f8fafb;border:1px solid var(--line,#d8e3e7);border-radius:12px;padding:11px}.home-item b{display:block}.rules{display:grid;gap:8px}.rule{background:#fff8db;border-right:4px solid #d7a31c;border-radius:10px;padding:10px}.route-editor{margin-top:18px}.edit-day{background:#fff;border:1px solid var(--line,#d8e3e7);border-radius:16px;padding:14px;margin-bottom:12px}.attraction-row{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center;padding:10px;border-top:1px solid #e8eef0}.attraction-row:first-of-type{border-top:0}.move-controls{display:flex;gap:6px;align-items:center}.move-controls select{padding:7px;border:1px solid #cfdde2;border-radius:8px;background:#fff}.move-controls button{border:0;background:#0d6f88;color:#fff;border-radius:8px;padding:7px 9px;cursor:pointer}.fixed-tag{font-size:.78rem;background:#eef6f8;border-radius:999px;padding:4px 7px;color:#52666f}.edit-note{font-size:.84rem;color:#667983}.home-kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin-top:12px}.home-kpi{background:#ffffff22;border:1px solid #ffffff55;border-radius:12px;padding:10px}.home-kpi b{display:block;font-size:1.2rem}.today-badge{display:inline-block;background:#fff;color:#0d6f88;border-radius:999px;padding:5px 9px;font-weight:800;margin-bottom:8px}@media(max-width:850px){.home-grid,.home-kpis{grid-template-columns:1fr}.attraction-row{grid-template-columns:1fr}.move-controls{flex-wrap:wrap}.move-controls select{flex:1;min-width:150px}}`;
document.head.appendChild(style);
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));}
function loadCustom(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');}catch(e){return null;}}
function saveCustom(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(D));}catch(e){}}
function applyCustom(){const saved=loadCustom();if(!saved||!Array.isArray(saved)||!Array.isArray(D))return;D.splice(0,D.length,...saved);}
function dayDate(i){return new Date(2026,8,23+i);} function dayLabel(i){return `${dayDate(i).getDate()}.9`}
function currentTripIndex(){const now=new Date(),local=new Date(now.toLocaleString('en-US',{timeZone:'Europe/Bucharest'})),y=local.getFullYear(),m=local.getMonth(),d=local.getDate();if(y===2026&&m===8&&d>=23&&d<=30)return d-23;return -1;}
function daysUntil(){return Math.max(0,Math.ceil((TRIP_START-Date.now())/86400000));}
function isFixedStop(name,desc=''){return /(hotel|swissôtel|swissotel|novotel|otp|airport|שדה|מלון|צ׳ק|צ'ק|חזרה למלון|יציאה)/i.test((name+' '+desc).toLowerCase());}
function navTo(page){document.querySelector(`.nav button[data-page="${page}"]`)?.click();}
function addHomeNav(){const nav=document.querySelector('.nav');if(!nav||nav.querySelector('[data-page="home"]'))return;const b=document.createElement('button');b.dataset.page='home';b.textContent='🏠 ראשי';nav.insertBefore(b,nav.firstChild);}
function homeStatus(){const idx=currentTripIndex();if(idx>=0)return{title:`היום · ${dayLabel(idx)} · ${D[idx]?.n||''}`,idx,badge:'היום בטיול'};if(Date.now()<TRIP_START)return{title:`הטיול מתחיל בעוד ${daysUntil()} ימים`,idx:0,badge:'לפני הטיול'};return{title:'הטיול הסתיים',idx:D.length-1,badge:'סיכום'};}
function buildHome(){if(document.getElementById('page-home'))return;const main=document.querySelector('main.wrap');if(!main)return;const sec=document.createElement('section');sec.id='page-home';sec.className='page';sec.innerHTML=`<div class="home-hero"><span class="today-badge" id="homeBadge"></span><h1 id="homeTitle">רומניה 2026</h1><div id="homeSub"></div><div class="home-kpis"><div class="home-kpi"><span>מלונות</span><b>7 לילות</b></div><div class="home-kpi"><span>רכב</span><b>Tiguan Auto</b></div><div class="home-kpi"><span>מסלול</span><b>23–30.9</b></div></div></div><div class="home-grid"><div><div class="card"><h2>📍 מה בתוכנית</h2><div id="homeToday" class="home-list"></div><button class="btn" id="openTodayRoute">פתח מסלול וערוך</button></div><div class="card" style="margin-top:14px"><h2>🗓️ סיכום המסלולים</h2><div id="homeDays" class="home-list"></div></div></div><div><div class="card"><h2>✅ כללים חשובים</h2><div class="rules"><div class="rule">⛽ לתדלק בתחנה גדולה ומסודרת ולשמור את <b>קבלת התדלוק</b>.</div><div class="rule">בבוקרשט: אפליקציית חניה <b>Parking Bucharest</b>.</div><div class="rule">לפני Transfăgărășan לבדוק פתיחת DN7C ומזג אוויר 24–48 שעות מראש.</div><div class="rule">Therme: לשים לב לכללי גובה/אזורי ילדים.</div><div class="rule">Klass Wagen: להגיע לנקודת המפגש ולהזמין Shuttle; כרטיס Visa/MasterCard פיזי.</div></div></div><div class="card" style="margin-top:14px"><h2>⚡ קיצורים</h2><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn" data-home-go="hotels">🏨 מלונות</button><button class="btn" data-home-go="car">🚙 רכב</button><button class="btn" data-home-go="calculator">🧮 מחשבון</button><button class="btn" data-home-go="summary">💰 סיכומים</button></div></div></div></div>`;main.insertBefore(sec,main.firstChild);sec.querySelectorAll('[data-home-go]').forEach(b=>b.onclick=()=>navTo(b.dataset.homeGo));sec.querySelector('#openTodayRoute').onclick=()=>{const st=homeStatus();navTo('trip');setTimeout(()=>{try{show(st.idx)}catch(e){}},50);};}
function renderHome(){buildHome();const s=homeStatus(),d=D[s.idx];document.getElementById('homeBadge').textContent=s.badge;document.getElementById('homeTitle').textContent=s.title;document.getElementById('homeSub').textContent=d?`${d.s.length} תחנות מתוכננות`:'';document.getElementById('homeToday').innerHTML=(d?.s||[]).map(x=>`<div class="home-item"><b>${esc(x[3])} · ${esc(x[0])}</b><span class="muted">${esc(x[4])}</span></div>`).join('');document.getElementById('homeDays').innerHTML=D.map((day,i)=>`<div class="home-item"><b>${dayLabel(i)} · ${esc(day.n)}</b><span class="muted">${day.s.filter(x=>!isFixedStop(x[0],x[4])).map(x=>esc(x[0])).join(' · ')||'נסיעות / מעבר'}</span></div>`).join('');}
function installRouteEditor(){const trip=document.getElementById('page-trip');if(!trip||trip.querySelector('.route-editor'))return;const h=document.createElement('div');h.className='route-editor';h.innerHTML=`<h2>✏️ עריכת מסלול ואטרקציות</h2><div class="card"><p>אפשר לעדכן את המסלול. השינויים נשמרים במכשיר.</p><div id="routeEditorDays"></div><button class="btn" id="resetItinerary">↩️ איפוס למסלול המקורי</button></div>`;trip.appendChild(h);h.querySelector('#resetItinerary').onclick=()=>{if(confirm('לאפס את כל השינויים במסלול?')){localStorage.removeItem(STORAGE_KEY);location.reload();}};renderRouteEditor();}
function renderRouteEditor(){const root=document.getElementById('routeEditorDays');if(!root)return;root.innerHTML=D.map((day,di)=>`<div class="edit-day"><h3>${dayLabel(di)} · ${esc(day.n)}</h3>${day.s.map((x,si)=>`<div class="attraction-row"><div><b>${esc(x[3])} · ${esc(x[0])}</b><div class="edit-note">${esc(x[4])}</div></div>${isFixedStop(x[0],x[4])?'<span class="fixed-tag">תחנת מסלול קבועה</span>':''}</div>`).join('')}</div>`).join('');}
function init(){if(typeof D==='undefined')return;applyCustom();addHomeNav();buildHome();installRouteEditor();renderHome();document.querySelector('.nav button[data-page="home"]')?.click();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();window.renderHome=renderHome;
})();