(()=>{
const TRIP_START=new Date('2026-09-19T00:20:00+03:00');
const TRIP_END=new Date('2026-09-30T12:55:00+03:00');
const STORAGE_KEY='romania-itinerary-v3';
const DEFAULT_DAYS=[
 {n:'שבת · נחיתה ופרדיאל',note:'הנחיתה מוקדמת מאוד. הצ׳ק-אין ב-Hotel Orizont מתחיל ב-16:00; כדאי לבדוק שמירת מזוודות או Early Check-in.',s:[['OTP',44.5711,26.085,'03:05','נחיתה בבוקרשט · טיסה LY9491'],['Klass Wagen Otopeni',44.566,26.075,'04:00','Shuttle ואיסוף Volkswagen Tiguan Automatic'],['Hotel Orizont Predeal',45.503,25.578,'06:30','הגעה לפרדיאל · לבדוק שמירת מזוודות / Early Check-in'],['Hotel Orizont Predeal',45.503,25.578,'16:00','צ׳ק-אין · לילה 1 מתוך 4']]},
 {n:'ראשון · פרדיאל',note:'טרם נקבע מסלול ליום הזה.',s:[['Hotel Orizont Predeal',45.503,25.578,'09:00','ארוחת בוקר / יום חופשי באזור פרדיאל'],['Hotel Orizont Predeal',45.503,25.578,'20:00','חזרה למלון']]},
 {n:'שני · פרדיאל',note:'טרם נקבע מסלול ליום הזה.',s:[['Hotel Orizont Predeal',45.503,25.578,'09:00','ארוחת בוקר / יום חופשי באזור פרדיאל'],['Hotel Orizont Predeal',45.503,25.578,'20:00','חזרה למלון']]},
 {n:'שלישי · פרדיאל',note:'טרם נקבע מסלול ליום הזה.',s:[['Hotel Orizont Predeal',45.503,25.578,'09:00','ארוחת בוקר / יום חופשי באזור פרדיאל'],['Hotel Orizont Predeal',45.503,25.578,'20:00','חזרה למלון']]},
 {n:'רביעי · מעבר לפויאנה בראשוב',note:'Hotel Orizont: צ׳ק-אאוט עד 12:00. Swissôtel: צ׳ק-אין החל מ-16:00.',s:[['Hotel Orizont Predeal',45.503,25.578,'11:30','צ׳ק-אאוט'],['Swissôtel Poiana Brașov',45.586,25.547,'16:00','צ׳ק-אין']]},
 {n:'חמישי · סלניק ובראשוב',note:'להגיע למכרה לפני 15:30.',s:[['Swissôtel Poiana Brașov',45.586,25.547,'09:00','ארוחת בוקר ויציאה'],['Salina Slănic Prahova',45.2341,25.9394,'11:30–14:30','מכרה מלח'],['Swissôtel Poiana Brașov',45.586,25.547,'16:30','בריכה'],['Piața Sfatului',45.6427,25.5887,'19:00','ערב בראשוב'],['Swissôtel Poiana Brașov',45.586,25.547,'22:00','חזרה למלון']]},
 {n:'שישי · פארק חבלים וסינאיה',note:'המגלשות והרכבלים תלויים במזג האוויר.',s:[['Swissôtel Poiana Brașov',45.586,25.547,'09:30','יציאה'],['Parc Aventura Brașov',45.618,25.641,'10:00–12:30','פארק חבלים + אוכל'],['Sinaia Gondola',45.3515,25.5507,'14:00','עלייה לכיוון Cota 2000'],['Sania Alpină Sinaia',45.351,25.552,'15:00–17:00','מגלשות הרים'],['Dimitrie Ghica Park',45.3525,25.5518,'17:15','פארק / קזינו / Bulevardul Carol'],['Swissôtel Poiana Brașov',45.586,25.547,'20:30','חזרה למלון']]},
 {n:'שבת · פלש ופארק מים',note:'לבדוק כרטיסים ושעת כניסה לפלש מראש.',s:[['Swissôtel Poiana Brașov',45.586,25.547,'10:00','יציאה'],['Peleș Castle',45.3599,25.5426,'11:00–14:00','טירה והשוק בחוץ'],['Paradisul Acvatic',45.6773,25.591,'15:30–19:30','פארק מים'],['Swissôtel Poiana Brașov',45.586,25.547,'20:30','חזרה למלון']]},
 {n:'ראשון · טרנספגראשן לבוקרשט',note:'לבדוק 24–48 שעות מראש שה-DN7C פתוח. Novotel: צ׳ק-אין החל מ-15:00.',s:[['Swissôtel Poiana Brașov',45.586,25.547,'09:00','צ׳ק-אאוט ויציאה'],['Bâlea Lake',45.6048,24.6177,'12:00','אגם · קרפ / קיורטוש / קפה'],['Vidraru Dam',45.366,24.63,'14:30','סכר'],['Novotel Bucharest City Centre',44.4371,26.0971,'19:00','צ׳ק-אין'],['Old Town Bucharest',44.4314,26.1004,'20:30','עיר עתיקה'],['Novotel Bucharest City Centre',44.4371,26.0971,'22:30','חזרה למלון']]},
 {n:'שני · אאוטלט, Jumbo ופארק',note:'',s:[['Novotel Bucharest City Centre',44.4371,26.0971,'09:30','יציאה'],['Fashion House Militari',44.4349,25.952,'10:00','אאוטלט'],['Jumbo Militari',44.434,25.948,'13:00','Jumbo'],['King Mihai I Park',44.4705,26.0825,'16:00','Herăstrău / שיט'],['Novotel Bucharest City Centre',44.4371,26.0971,'19:00','חזרה למלון']]},
 {n:'שלישי · AFI ו-Therme',note:'Therme: הילדים בני 9 ו-12 - אזור Galaxy; לבדוק מגבלות גיל וגובה בכל מגלשה.',s:[['Novotel Bucharest City Centre',44.4371,26.0971,'09:30','יציאה'],['AFI Cotroceni',44.4305,26.0527,'10:00','Primark · החלקה · Museum of Senses'],['Therme București',44.6062,26.0804,'14:00–20:00','Therme · Galaxy'],['Novotel Bucharest City Centre',44.4371,26.0971,'21:00','חזרה למלון']]},
 {n:'רביעי · טיסה חזרה',note:'Klass Wagen: החזרת רכב 08:30. טיסת LY574 ממריאה ב-10:25.',s:[['Novotel Bucharest City Centre',44.4371,26.0971,'06:45','צ׳ק-אאוט'],['Klass Wagen Otopeni',44.566,26.075,'08:30','החזרת הרכב'],['OTP',44.5711,26.085,'09:00','טרמינל לטיסת LY574'],['TLV',32.0055,34.8854,'12:55','נחיתה בנתב״ג Terminal 3']]}
];
const style=document.createElement('style');
style.textContent=`.home-hero{background:linear-gradient(135deg,#0d6f88,#1496b5);color:#fff;border-radius:20px;padding:22px;margin-bottom:16px}.home-hero h1{margin:0 0 6px}.home-grid{display:grid;grid-template-columns:1.3fr .7fr;gap:14px}.home-list{display:grid;gap:9px}.home-item{background:#f8fafb;border:1px solid var(--line,#d8e3e7);border-radius:12px;padding:11px}.home-item b{display:block}.rules{display:grid;gap:8px}.rule{background:#fff8db;border-right:4px solid #d7a31c;border-radius:10px;padding:10px}.route-editor{margin-top:18px}.edit-day{background:#fff;border:1px solid var(--line,#d8e3e7);border-radius:16px;padding:14px;margin-bottom:12px}.attraction-row{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center;padding:10px;border-top:1px solid #e8eef0}.attraction-row:first-of-type{border-top:0}.fixed-tag{font-size:.78rem;background:#eef6f8;border-radius:999px;padding:4px 7px;color:#52666f}.edit-note{font-size:.84rem;color:#667983}.home-kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin-top:12px}.home-kpi{background:#ffffff22;border:1px solid #ffffff55;border-radius:12px;padding:10px}.home-kpi b{display:block;font-size:1.2rem}.today-badge{display:inline-block;background:#fff;color:#0d6f88;border-radius:999px;padding:5px 9px;font-weight:800;margin-bottom:8px}@media(max-width:850px){.home-grid,.home-kpis{grid-template-columns:1fr}.attraction-row{grid-template-columns:1fr}}`;
document.head.appendChild(style);
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function seedDays(){if(!Array.isArray(window.D)&&typeof D==='undefined')return;D.splice(0,D.length,...DEFAULT_DAYS.map(x=>({n:x.n,note:x.note,s:x.s.map(y=>[...y])})));}
function loadCustom(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'null')}catch(e){return null}}
function applyCustom(){const saved=loadCustom();if(Array.isArray(saved)&&saved.length===12)D.splice(0,D.length,...saved)}
function dayDate(i){return new Date(2026,8,19+i)}
function dayLabel(i){return `${dayDate(i).getDate()}.9`}
function currentTripIndex(){const now=new Date(),local=new Date(now.toLocaleString('en-US',{timeZone:'Europe/Bucharest'})),y=local.getFullYear(),m=local.getMonth(),d=local.getDate();if(y===2026&&m===8&&d>=19&&d<=30)return d-19;return -1}
function daysUntil(){return Math.max(0,Math.ceil((TRIP_START-Date.now())/86400000))}
function isFixedStop(name,desc=''){return /(hotel|swissôtel|swissotel|novotel|orizont|otp|tlv|airport|klass|שדה|מלון|צ׳ק|צ'ק|חזרה למלון|יציאה)/i.test((name+' '+desc).toLowerCase())}
function navTo(page){document.querySelector(`.nav button[data-page="${page}"]`)?.click()}
function addHomeNav(){const nav=document.querySelector('.nav');if(!nav||nav.querySelector('[data-page="home"]'))return;const b=document.createElement('button');b.dataset.page='home';b.textContent='🏠 ראשי';nav.insertBefore(b,nav.firstChild)}
function homeStatus(){const idx=currentTripIndex();if(idx>=0)return{title:`היום · ${dayLabel(idx)} · ${D[idx]?.n||''}`,idx,badge:'היום בטיול'};if(Date.now()<TRIP_START)return{title:`הטיול מתחיל בעוד ${daysUntil()} ימים`,idx:0,badge:'לפני הטיול'};return{title:'הטיול הסתיים',idx:D.length-1,badge:'סיכום'}}
function buildHome(){if(document.getElementById('page-home'))return;const main=document.querySelector('main.wrap');if(!main)return;const sec=document.createElement('section');sec.id='page-home';sec.className='page';sec.innerHTML=`<div class="home-hero"><span class="today-badge" id="homeBadge"></span><h1 id="homeTitle">רומניה 2026</h1><div id="homeSub"></div><div class="home-kpis"><div class="home-kpi"><span>מלונות</span><b>11 לילות</b></div><div class="home-kpi"><span>רכב</span><b>19–30.9</b></div><div class="home-kpi"><span>מסלול</span><b>19–30.9</b></div></div></div><div class="home-grid"><div><div class="card"><h2>📍 מה בתוכנית</h2><div id="homeToday" class="home-list"></div><button class="btn" id="openTodayRoute">פתח מסלול</button></div><div class="card" style="margin-top:14px"><h2>🗓️ כל ימי הטיול</h2><div id="homeDays" class="home-list"></div></div></div><div><div class="card"><h2>✅ כללים חשובים</h2><div class="rules"><div class="rule">✈️ הלוך: LY9491 · 19.9 00:20 → 03:05 · TAROM עבור EL AL.</div><div class="rule">🚙 Klass Wagen: 19.9 04:00 → 30.9 08:30.</div><div class="rule">⛽ לתדלק בתחנה גדולה ומסודרת ולשמור קבלה.</div><div class="rule">בבוקרשט: <b>Parking Bucharest</b>.</div><div class="rule">לפני Transfăgărășan לבדוק DN7C ומזג אוויר 24–48 שעות מראש.</div><div class="rule">Therme: הילדים בני 9 ו-12 — Galaxy; לבדוק מגבלה בכל מגלשה.</div></div></div></div></div>`;main.insertBefore(sec,main.firstChild);sec.querySelector('#openTodayRoute').onclick=()=>{const st=homeStatus();navTo('trip');setTimeout(()=>{try{show(st.idx)}catch(e){}},50)}}
function renderHome(){buildHome();const s=homeStatus(),d=D[s.idx];document.getElementById('homeBadge').textContent=s.badge;document.getElementById('homeTitle').textContent=s.title;document.getElementById('homeSub').textContent=d?`${d.s.length} תחנות מתוכננות`:'';document.getElementById('homeToday').innerHTML=(d?.s||[]).map(x=>`<div class="home-item"><b>${esc(x[3])} · ${esc(x[0])}</b><span class="muted">${esc(x[4])}</span></div>`).join('');document.getElementById('homeDays').innerHTML=D.map((day,i)=>`<div class="home-item"><b>${dayLabel(i)} · ${esc(day.n)}</b><span class="muted">${day.s.filter(x=>!isFixedStop(x[0],x[4])).map(x=>esc(x[0])).join(' · ')||'מלון / מעבר / טיסה'}</span></div>`).join('')}
function rebuildTrip(){const tabs=document.getElementById('tabs');if(tabs){tabs.innerHTML=D.map((d,i)=>`<button class="tab" onclick="show(${i})">${dayLabel(i)}</button>`).join('');try{show(0)}catch(e){}}}
function installRouteEditor(){const trip=document.getElementById('page-trip');if(!trip||trip.querySelector('.route-editor'))return;const h=document.createElement('div');h.className='route-editor';h.innerHTML=`<h2>✏️ עריכת מסלול ואטרקציות</h2><div class="card"><p>הימים 19–22 עדיין פתוחים לשינויים. המסלול נשמר במכשיר ובסנכרון המשפחתי.</p><div id="routeEditorDays"></div><button class="btn" id="resetItinerary">↩️ איפוס למסלול המעודכן</button></div>`;trip.appendChild(h);h.querySelector('#resetItinerary').onclick=()=>{if(confirm('לאפס את השינויים למסלול המעודכן?')){localStorage.removeItem(STORAGE_KEY);location.reload()}};renderRouteEditor()}
function renderRouteEditor(){const root=document.getElementById('routeEditorDays');if(!root)return;root.innerHTML=D.map((day,di)=>`<div class="edit-day"><h3>${dayLabel(di)} · ${esc(day.n)}</h3>${day.s.map(x=>`<div class="attraction-row"><div><b>${esc(x[3])} · ${esc(x[0])}</b><div class="edit-note">${esc(x[4])}</div></div>${isFixedStop(x[0],x[4])?'<span class="fixed-tag">תחנה קבועה</span>':''}</div>`).join('')}</div>`).join('')}
function init(){if(typeof D==='undefined')return;seedDays();applyCustom();addHomeNav();buildHome();rebuildTrip();installRouteEditor();renderHome();document.querySelector('.nav button[data-page="home"]')?.click()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();window.renderHome=renderHome;
})();