(()=>{
'use strict';
const items=[
 {key:'lukoil',match:'Lukoil',title:'לא לתדלק בתחנת Lukoil',desc:'תזכורת לטיול ברומניה: לא לתדלק בתחנת Lukoil.',start:'20260923T184500Z',end:'20260923T190000Z'},
 {key:'parking',match:'Parking Bucharest',title:'להפעיל Parking Bucharest',desc:'בבוקרשט: להשתמש באפליקציית Parking Bucharest לחניה.',start:'20260927T153000Z',end:'20260927T154500Z'},
 {key:'dn7c',match:'Transfăgărășan',title:'לבדוק DN7C ומזג אוויר',desc:'לבדוק פתיחת כביש DN7C ומזג אוויר לפני הנסיעה ב-Transfăgărășan.',start:'20260925T060000Z',end:'20260925T061500Z',second:{title:'בדיקה נוספת: DN7C ומזג אוויר',desc:'בדיקה נוספת 24 שעות לפני: פתיחת DN7C ומזג אוויר.',start:'20260926T060000Z',end:'20260926T061500Z'}},
 {key:'therme',match:'Therme',title:'Therme - לבדוק כללי גובה וילדים',desc:'לפני Therme: לבדוק כללי גובה, גיל ואזורי ילדים.',start:'20260929T070000Z',end:'20260929T071500Z'},
 {key:'klass',match:'Klass Wagen',title:'Klass Wagen - Shuttle וכרטיס אשראי',desc:'לאחר הנחיתה: להגיע לנקודת המפגש, להזמין Shuttle, ולהכין Visa/MasterCard פיזי על שם בעל החוזה.',start:'20260923T180000Z',end:'20260923T181500Z'}
];
function escICS(s){return String(s).replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;')}
function icsEvent(x){return `BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//RomaniaTrip//HE\r\nCALSCALE:GREGORIAN\r\nMETHOD:PUBLISH\r\nBEGIN:VEVENT\r\nUID:${x.key||Date.now()}-${Date.now()}@romaniatrip\r\nDTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z/,'Z')}\r\nDTSTART:${x.start}\r\nDTEND:${x.end}\r\nSUMMARY:${escICS(x.title)}\r\nDESCRIPTION:${escICS(x.desc)}\r\nBEGIN:VALARM\r\nTRIGGER:-PT15M\r\nACTION:DISPLAY\r\nDESCRIPTION:${escICS(x.title)}\r\nEND:VALARM\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n`}
function downloadICS(x){const blob=new Blob([icsEvent(x)],{type:'text/calendar;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(x.key||'reminder')+'.ics';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function gcal(x){const u=new URL('https://calendar.google.com/calendar/render');u.searchParams.set('action','TEMPLATE');u.searchParams.set('text',x.title);u.searchParams.set('details',x.desc);u.searchParams.set('dates',x.start.replace('Z','')+'/'+x.end.replace('Z',''));u.searchParams.set('ctz','Europe/Bucharest');window.open(u.toString(),'_blank')}
function addButtons(){const rules=[...document.querySelectorAll('.rule')];items.forEach(x=>{const rule=rules.find(r=>r.textContent.includes(x.match));if(!rule||rule.querySelector(`[data-reminder="${x.key}"]`))return;const wrap=document.createElement('div');wrap.style='display:flex;gap:7px;flex-wrap:wrap;margin-top:8px';wrap.innerHTML=`<button class="btn" type="button" data-reminder="${x.key}">🔔 צור התראה</button><button class="btn" type="button" data-gcal="${x.key}" style="background:#466">Google Calendar</button>${x.second?`<button class="btn" type="button" data-second="${x.key}" style="background:#805400">🔔 גם 24 שעות לפני</button>`:''}`;rule.appendChild(wrap);wrap.querySelector(`[data-reminder="${x.key}"]`).onclick=()=>downloadICS(x);wrap.querySelector(`[data-gcal="${x.key}"]`).onclick=()=>gcal(x);if(x.second)wrap.querySelector(`[data-second="${x.key}"]`).onclick=()=>downloadICS({...x.second,key:x.key+'-24h'});});}
function init(){addButtons();const obs=new MutationObserver(addButtons);obs.observe(document.body,{childList:true,subtree:true});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();