(()=>{
'use strict';
const ENDPOINT_KEY='romania-sync-endpoint';
const MEMBER_KEY='romania-sync-member';
const MIGRATED_KEY='romania-sync-migrated-v1';
const LAST_SYNC_KEY='romania-last-sync';
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function navTo(page){document.querySelector(`header .nav button[data-page="${page}"]`)?.click()}
function injectStyle(){if(document.getElementById('settingsSupportStyle'))return;const s=document.createElement('style');s.id='settingsSupportStyle';s.textContent=`
#page-settings{max-width:980px;margin:0 auto}.settings-grid{display:grid;grid-template-columns:1.15fr .85fr;gap:14px}.settings-card{background:var(--card,#fff);border:1px solid var(--line,#d8e3e7);border-radius:18px;padding:18px}.settings-card h2{margin:0 0 12px}.settings-fields{display:grid;gap:11px}.settings-field{display:grid;gap:5px}.settings-field label{font-weight:800}.settings-field input{width:100%;min-width:0;padding:11px 12px;border:1px solid var(--line,#d8e3e7);border-radius:11px;background:var(--card,#fff);color:var(--text,#17313b);font-size:16px}.settings-actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:14px}.settings-actions button{border:0;border-radius:10px;padding:10px 13px;font-weight:800;cursor:pointer;background:var(--p,#31473A);color:#fff}.settings-actions button.secondary{background:var(--soft,#eef6f8);color:var(--text,#17313b);border:1px solid var(--line,#d8e3e7)}.settings-actions button.danger{background:#743B46;color:#fff}.settings-state{display:grid;gap:8px}.settings-state-row{display:flex;justify-content:space-between;gap:12px;padding:10px 0;border-bottom:1px solid var(--line,#d8e3e7)}.settings-state-row:last-child{border-bottom:0}.settings-state-row b{direction:ltr;unicode-bidi:isolate;text-align:left;overflow-wrap:anywhere}.settings-note{margin-top:10px;padding:11px 12px;border-radius:11px;background:var(--soft,#eef6f8);color:var(--muted,#667983)}#settingsMsg{min-height:22px;margin-top:10px;font-weight:800}.settings-ok{color:#4e8b61}.settings-warn{color:#b68a4c}:root[data-theme="dark"] .settings-card{background:var(--card)!important;border-color:var(--line)!important}:root[data-theme="dark"] .settings-field input{background:#202821!important;color:var(--text)!important;border-color:var(--line)!important}@media(max-width:760px){#page-settings{width:100%;max-width:100%}.settings-grid{grid-template-columns:1fr}.settings-card{padding:14px}.settings-state-row{display:grid;gap:4px}.settings-actions button{flex:1 1 140px}}
`;document.head.appendChild(s)}
function ensureNav(){const nav=document.querySelector('header .nav');if(!nav||nav.querySelector('[data-page="settings"]'))return;const b=document.createElement('button');b.type='button';b.dataset.page='settings';b.textContent='⚙️ הגדרות';nav.appendChild(b)}
function ensurePage(){if(document.getElementById('page-settings'))return;const main=document.querySelector('main.wrap');if(!main)return;const sec=document.createElement('section');sec.id='page-settings';sec.className='page';sec.innerHTML=`<h1>⚙️ הגדרות ותמיכה</h1><div class="settings-grid"><div class="settings-card"><h2>☁️ סנכרון משפחתי</h2><div class="settings-fields"><div class="settings-field"><label for="settingsSyncEndpoint">כתובת Google Apps Script Web App</label><input id="settingsSyncEndpoint" type="url" inputmode="url" autocomplete="off" placeholder="https://script.google.com/macros/s/..."></div><div class="settings-field"><label for="settingsMember">שם המכשיר / בן המשפחה</label><input id="settingsMember" type="text" autocomplete="off" placeholder="Family"></div></div><div class="settings-actions"><button id="settingsSaveSync" type="button">שמור וסנכרן</button><button id="settingsSyncNow" type="button" class="secondary">סנכרן עכשיו</button><button id="settingsRemoveSync" type="button" class="danger">הסר הגדרת סנכרון</button></div><div id="settingsMsg"></div></div><div class="settings-card"><h2>📱 מצב האפליקציה</h2><div class="settings-state"><div class="settings-state-row"><span>חיבור אינטרנט</span><b id="settingsOnline">—</b></div><div class="settings-state-row"><span>סנכרון מוגדר</span><b id="settingsSyncConfigured">—</b></div><div class="settings-state-row"><span>סנכרון אחרון</span><b id="settingsLastSync">—</b></div><div class="settings-state-row"><span>גרסת ממשק</span><b>2026.09.13</b></div></div></div><div class="settings-card"><h2>🧹 ניקוי קאש</h2><p>מנקה את קבצי האתר השמורים בדפדפן ומאלץ טעינה של הגרסה החדשה.</p><div class="settings-note">הפעולה לא מוחקת את המסלול, המשימות, ההוצאות או הגדרות הסנכרון השמורות במכשיר.</div><div class="settings-actions"><button id="settingsClearCache" type="button">נקה קאש ורענן</button></div></div><div class="settings-card"><h2>🛟 תמיכה</h2><p>אם משהו באתר לא מתעדכן, נסה קודם <b>נקה קאש ורענן</b>. אם הסנכרון לא עובד, בדוק שהכתובת למעלה שמורה ושהמכשיר מחובר לאינטרנט.</p><div class="settings-actions"><button id="settingsBackHome" type="button" class="secondary">חזרה לראשי</button></div></div></div>`;main.appendChild(sec)}
function ensureMoreButton(){const grid=document.querySelector('#moreSheet .more-grid');if(!grid||grid.querySelector('[data-go="settings"]'))return;const b=document.createElement('button');b.type='button';b.dataset.go='settings';b.innerHTML='<span>⚙️</span>הגדרות';grid.appendChild(b);b.onclick=()=>{document.getElementById('moreSheet')?.classList.remove('open');navTo('settings')}}
function fmtLastSync(v){if(!v)return 'לא בוצע';const d=new Date(v);if(Number.isNaN(d.getTime()))return 'לא ידוע';try{return new Intl.DateTimeFormat('he-IL',{dateStyle:'short',timeStyle:'short'}).format(d)}catch(e){return d.toLocaleString()}}
function refresh(){const ep=localStorage.getItem(ENDPOINT_KEY)||'',member=localStorage.getItem(MEMBER_KEY)||'';const e=document.getElementById('settingsSyncEndpoint'),m=document.getElementById('settingsMember');if(e&&document.activeElement!==e)e.value=ep;if(m&&document.activeElement!==m)m.value=member;const on=document.getElementById('settingsOnline');if(on)on.textContent=navigator.onLine?'אונליין':'אופליין';const sc=document.getElementById('settingsSyncConfigured');if(sc)sc.textContent=ep?'כן':'לא';const ls=document.getElementById('settingsLastSync');if(ls)ls.textContent=fmtLastSync(localStorage.getItem(LAST_SYNC_KEY))}
function msg(text,ok=true){const e=document.getElementById('settingsMsg');if(!e)return;e.textContent=text;e.className=ok?'settings-ok':'settings-warn'}
async function saveSync(){const ep=(document.getElementById('settingsSyncEndpoint')?.value||'').trim();const member=(document.getElementById('settingsMember')?.value||'').trim();if(ep&&!/^https:\/\//i.test(ep)){msg('כתובת הסנכרון חייבת להתחיל ב־https://',false);return}if(ep)localStorage.setItem(ENDPOINT_KEY,ep);else localStorage.removeItem(ENDPOINT_KEY);if(member)localStorage.setItem(MEMBER_KEY,member);else localStorage.removeItem(MEMBER_KEY);localStorage.removeItem(MIGRATED_KEY);msg(ep?'נשמר. מתחיל סנכרון…':'הגדרת הסנכרון הוסרה.');refresh();try{if(window.RomaniaFamilySync?.setEndpoint)await window.RomaniaFamilySync.setEndpoint(ep);else if(window.RomaniaFamilySync?.sync)await window.RomaniaFamilySync.sync();msg(ep?'ההגדרות נשמרו והסנכרון הופעל.':'הגדרת הסנכרון הוסרה.');refresh()}catch(e){msg('ההגדרות נשמרו, אבל הסנכרון לא הצליח כרגע.',false)}}
async function syncNow(){if(!localStorage.getItem(ENDPOINT_KEY)){msg('אין כרגע כתובת סנכרון מוגדרת.',false);return}msg('מסנכרן…');try{await window.RomaniaFamilySync?.sync?.();msg('הסנכרון הסתיים.');refresh()}catch(e){msg('הסנכרון לא הצליח כרגע.',false)}}
async function removeSync(){localStorage.removeItem(ENDPOINT_KEY);localStorage.removeItem(MIGRATED_KEY);try{await window.RomaniaFamilySync?.setEndpoint?.('')}catch(e){}msg('הגדרת הסנכרון הוסרה מהמכשיר.');refresh()}
async function clearCache(){const b=document.getElementById('settingsClearCache');if(b){b.disabled=true;b.textContent='מנקה…'}try{if('caches'in window){const names=await caches.keys();await Promise.all(names.map(n=>caches.delete(n)))}if('serviceWorker'in navigator){const regs=await navigator.serviceWorker.getRegistrations();await Promise.all(regs.map(r=>r.update().catch(()=>{})))}const u=new URL(location.href);u.searchParams.set('_fresh',Date.now().toString());location.replace(u.toString())}catch(e){if(b){b.disabled=false;b.textContent='נקה קאש ורענן'}msg('לא הצלחתי לנקות את הקאש אוטומטית.',false)}}
function wire(){document.getElementById('settingsSaveSync')?.addEventListener('click',saveSync);document.getElementById('settingsSyncNow')?.addEventListener('click',syncNow);document.getElementById('settingsRemoveSync')?.addEventListener('click',removeSync);document.getElementById('settingsClearCache')?.addEventListener('click',clearCache);document.getElementById('settingsBackHome')?.addEventListener('click',()=>navTo('home'));window.addEventListener('online',refresh);window.addEventListener('offline',refresh);window.addEventListener('storage',refresh)}
function init(){injectStyle();ensureNav();ensurePage();ensureMoreButton();wire();refresh();setTimeout(()=>{ensureNav();ensureMoreButton();refresh()},700);new MutationObserver(()=>ensureMoreButton()).observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();