(()=>{
'use strict';
const EXP_KEY='romania-manual-expenses-v2';
const OLD_KEY='romania-manual-expenses';
const FX_KEY='romania-fx-v2';
const BASE={monopolyRON:546.75,orizontILS:2255,swissEUR:1268.70,novotelILS:2968,carEUR:527,flightsILS:7035};
let fx={EURILS:0,RONILS:0,USDILS:0};
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const shekel=n=>'₪'+Math.round(Number(n)||0).toLocaleString('he-IL');
function readExpenses(){try{let raw=localStorage.getItem(EXP_KEY);if(!raw){raw=localStorage.getItem(OLD_KEY);if(raw)localStorage.setItem(EXP_KEY,raw)}const v=JSON.parse(raw||'[]');return Array.isArray(v)?v:[]}catch(e){return []}}
function writeExpenses(v){localStorage.setItem(EXP_KEY,JSON.stringify(v));localStorage.setItem(OLD_KEY,JSON.stringify(v));window.RomaniaFamilySync?.sync?.()}
function original(x){const n=Number(x.amount).toLocaleString('he-IL',{maximumFractionDigits:2});return x.currency==='EUR'?`€${n}`:x.currency==='USD'?`$${n}`:x.currency==='ILS'?`₪${n}`:`${n} RON`}
function toIls(amount,c){const n=Number(amount)||0;if(c==='ILS')return n;if(c==='EUR')return n*fx.EURILS;if(c==='RON')return n*fx.RONILS;if(c==='USD')return n*fx.USDILS;return 0}
function renderExpenses(){const table=$('expenseTable'),rows=$('manualSummaryRows'),list=readExpenses();if(table){table.innerHTML=list.length?'':'<div class="muted">עדיין לא נוספו הוצאות ידניות.</div>';list.forEach((x,i)=>{const converted=toIls(x.amount,x.currency);table.insertAdjacentHTML('beforeend',`<div class="expense-item"><b class="ltr">${esc(original(x))}</b><span class="summary-ils">${converted?shekel(converted):x.currency==='ILS'?shekel(x.amount):'ממתין לשער'}</span><span>${esc(x.description||'הוצאה נוספת')}</span><button class="danger-btn" type="button" data-del-exp="${i}">מחק</button></div>`)});table.querySelectorAll('[data-del-exp]').forEach(b=>b.onclick=async()=>{const a=readExpenses(),idx=Number(b.dataset.delExp),x=a[idx];if(!x)return;const label=x.description||'הוצאה נוספת';const ok=window.confirm(`למחוק את "${label}" (${original(x)})?\n\nאם תאשר, ההוצאה תימחק גם מהשרת.`);if(!ok)return;a.splice(idx,1);localStorage.setItem(EXP_KEY,JSON.stringify(a));localStorage.setItem(OLD_KEY,JSON.stringify(a));renderAll();if(x.id!=null&&window.RomaniaFamilySync?.deleteExpense)await window.RomaniaFamilySync.deleteExpense(x.id);else window.RomaniaFamilySync?.sync?.()})}if(rows){rows.innerHTML='';list.forEach(x=>{const converted=toIls(x.amount,x.currency);rows.insertAdjacentHTML('beforeend',`<div class="summary-row"><div><b>➕ ${esc(x.description||'הוצאה נוספת')}</b></div><div class="ltr">${esc(original(x))}</div><div class="summary-ils">${converted?shekel(converted):x.currency==='ILS'?shekel(x.amount):'ממתין לשער'}</div></div>`)})}}
function ensureRows(){const list=document.querySelector('#page-summary .summary-list');if(!list)return;function add(id,html,before){if(document.getElementById(id))return;const r=document.createElement('div');r.id=id;r.className='summary-row';r.innerHTML=html;list.insertBefore(r,before||list.firstChild)}add('sumMonopolyRow','<div><b>🏨 Monopoly Hotel · Otopeni</b><div class="muted">18–19.9 · לילה 1 · שולם</div></div><div class="ltr">546.75 RON</div><div class="summary-ils" id="sumMonopoly">—</div>');add('sumOrizontRow','<div><b>🏨 Hotel Orizont · Predeal</b><div class="muted">19–23.9 · 4 לילות</div></div><div class="ltr">₪2,255</div><div class="summary-ils">₪2,255</div>');add('sumFlightsRow','<div><b>✈️ טיסות</b><div class="muted">LY9491 · LY574</div></div><div class="ltr">₪7,035</div><div class="summary-ils">₪7,035</div>',list.querySelector('.summary-row.total'))}
function renderAll(){ensureRows();renderExpenses();if(!(fx.EURILS&&fx.RONILS))return;const monopoly=BASE.monopolyRON*fx.RONILS,swiss=BASE.swissEUR*fx.EURILS,car=BASE.carEUR*fx.EURILS;const manual=readExpenses().reduce((t,x)=>t+toIls(x.amount,x.currency),0);if($('sumMonopoly'))$('sumMonopoly').textContent=shekel(monopoly);if($('sumSwiss'))$('sumSwiss').textContent=shekel(swiss);if($('sumNovotel'))$('sumNovotel').textContent=shekel(BASE.novotelILS);if($('sumCar'))$('sumCar').textContent=shekel(car);if($('summaryGrandTotal'))$('summaryGrandTotal').textContent=shekel(monopoly+BASE.orizontILS+BASE.novotelILS+BASE.flightsILS+swiss+car+manual);if($('summaryRates'))$('summaryRates').textContent=`€1 = ₪${fx.EURILS.toFixed(3)} · $1 = ₪${fx.USDILS.toFixed(3)} · 1 RON = ₪${fx.RONILS.toFixed(3)}`;}
async function fetchJson(url,timeout=8000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{cache:'no-store',signal:c.signal});if(!r.ok)throw new Error(String(r.status));return await r.json()}finally{clearTimeout(t)}}
async function loadFx(){const status=$('summaryRateStatus');try{const c=JSON.parse(localStorage.getItem(FX_KEY)||'null');if(c?.rates?.EURILS){fx=c.rates;renderAll();if(status)status.textContent='🟡 מציג שער שמור ומעדכן…'}}catch(e){}let rates=null;try{const j=await fetchJson('https://api.frankfurter.app/latest?from=EUR&to=ILS,RON,USD');const ei=+j.rates?.ILS,er=+j.rates?.RON,eu=+j.rates?.USD;if(ei>0&&er>0&&eu>0)rates={EURILS:ei,RONILS:ei/er,USDILS:ei/eu}}catch(e){}if(!rates){try{const j=await fetchJson('https://open.er-api.com/v6/latest/EUR');const ei=+j.rates?.ILS,er=+j.rates?.RON,eu=+j.rates?.USD;if(ei>0&&er>0&&eu>0)rates={EURILS:ei,RONILS:ei/er,USDILS:ei/eu}}catch(e){}}if(rates){fx=rates;localStorage.setItem(FX_KEY,JSON.stringify({rates,time:Date.now()}));renderAll();if(status)status.textContent='🟢 שערי ההמרה עודכנו אונליין'}else if(fx.EURILS){if(status)status.textContent='🟡 אין עדכון כרגע · משתמש בשער האחרון שנשמר'}else if(status)status.textContent='🔴 אין כרגע שער המרה זמין'}
function addExpense(){const amount=Number($('expenseAmount')?.value),currency=$('expenseCurrency')?.value||'RON',description=($('expenseDescription')?.value||'').trim();if(!(amount>0)){alert('יש להזין מחיר');return}const a=readExpenses();a.push({id:Date.now(),amount,currency,description,createdAt:new Date().toISOString()});writeExpenses(a);if($('expenseAmount'))$('expenseAmount').value='';if($('expenseDescription'))$('expenseDescription').value='';renderAll()}
function removeEstimates(){['sumParking','sumFuel','sumFuelRon','sumFuelDetails'].forEach(id=>{const el=$(id);const row=el?.closest('.summary-row');if(row)row.remove()});document.querySelectorAll('#page-summary .summary-row').forEach(r=>{const t=r.textContent||'';if(/דלק צפוי|חניה צפויה|חניות צפויות|חניה · Swiss/i.test(t))r.remove()})}\nfunction init(){const sel=$('expenseCurrency');if(sel&&!sel.querySelector('option[value="USD"]')){const o=document.createElement('option');o.value='USD';o.textContent='USD ($)';sel.insertBefore(o,sel.querySelector('option[value="ILS"]'))}const total=$('summaryGrandTotal')?.closest('.summary-row');if(total){const b=total.querySelector('b');if(b)b.textContent='סה״כ:';const note=total.querySelector('div div');if(note)note.textContent='שולם או התחייבת לשלם נכון לעכשיו'}const old=$('addExpenseBtn');if(old){const fresh=old.cloneNode(true);old.replaceWith(fresh);fresh.addEventListener('click',addExpense)}ensureRows();removeEstimates();renderAll();loadFx();document.querySelector('[data-page="summary"]')?.addEventListener('click',()=>{renderAll();if(!fx.EURILS)loadFx()});window.addEventListener('storage',e=>{if(e.key===EXP_KEY||e.key===OLD_KEY)renderAll()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();window.RomaniaSummary={render:renderAll,reloadRates:loadFx};
})();