(()=>{
'use strict';
const EXP_KEY='romania-manual-expenses-v2';
const OLD_KEY='romania-manual-expenses';
const FX_KEY='romania-fx-v2';
const BASE={orizontILS:2255,flightsILS:7035,swissEUR:1268.70,novotelRON:4498.01,carEUR:527};
let fx={EURILS:0,RONILS:0,USDILS:0};
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const shekel=n=>'₪'+Math.round(Number(n)||0).toLocaleString('he-IL');
function readExpenses(){try{let raw=localStorage.getItem(EXP_KEY);if(!raw){raw=localStorage.getItem(OLD_KEY);if(raw)localStorage.setItem(EXP_KEY,raw)}const v=JSON.parse(raw||'[]');return Array.isArray(v)?v:[]}catch(e){return []}}
function writeExpenses(v){localStorage.setItem(EXP_KEY,JSON.stringify(v));localStorage.setItem(OLD_KEY,JSON.stringify(v));}
function original(x){const n=Number(x.amount).toLocaleString('he-IL',{maximumFractionDigits:2});return x.currency==='EUR'?`€${n}`:x.currency==='USD'?`$${n}`:x.currency==='ILS'?`₪${n}`:`${n} RON`;}
function toIls(amount,c){const n=Number(amount)||0;if(c==='ILS')return n;if(c==='EUR')return n*fx.EURILS;if(c==='RON')return n*fx.RONILS;if(c==='USD')return n*fx.USDILS;return 0;}
function renderExpenses(){const table=$('expenseTable'),rows=$('manualSummaryRows'),list=readExpenses();if(table){table.innerHTML=list.length?'':'<div class="muted">עדיין לא נוספו הוצאות ידניות.</div>';list.forEach((x,i)=>{const converted=toIls(x.amount,x.currency);table.insertAdjacentHTML('beforeend',`<div class="expense-item"><b class="ltr">${esc(original(x))}</b><span class="summary-ils">${converted?shekel(converted):x.currency==='ILS'?shekel(x.amount):'ממתין לשער'}</span><span>${esc(x.description||'הוצאה נוספת')}</span><button class="danger-btn" type="button" data-del-exp="${i}">מחק</button></div>`)});table.querySelectorAll('[data-del-exp]').forEach(b=>b.onclick=()=>{const a=readExpenses();a.splice(Number(b.dataset.delExp),1);writeExpenses(a);renderAll();});}if(rows){rows.innerHTML='';list.forEach(x=>{const converted=toIls(x.amount,x.currency);rows.insertAdjacentHTML('beforeend',`<div class="summary-row"><div><b>➕ ${esc(x.description||'הוצאה נוספת')}</b></div><div class="ltr">${esc(original(x))}</div><div class="summary-ils">${converted?shekel(converted):x.currency==='ILS'?shekel(x.amount):'ממתין לשער'}</div></div>`)});}}
function renderAll(){renderExpenses();if($('sumOrizont'))$('sumOrizont').textContent=shekel(BASE.orizontILS);if($('sumFlights'))$('sumFlights').textContent=shekel(BASE.flightsILS);if(!(fx.EURILS&&fx.RONILS))return;const swiss=BASE.swissEUR*fx.EURILS,novo=BASE.novotelRON*fx.RONILS,car=BASE.carEUR*fx.EURILS;const manual=readExpenses().reduce((t,x)=>t+toIls(x.amount,x.currency),0);if($('sumSwiss'))$('sumSwiss').textContent=shekel(swiss);if($('sumNovotel'))$('sumNovotel').textContent=shekel(novo);if($('sumCar'))$('sumCar').textContent=shekel(car);if($('summaryGrandTotal'))$('summaryGrandTotal').textContent=shekel(BASE.orizontILS+BASE.flightsILS+swiss+novo+car+manual);if($('summaryRates'))$('summaryRates').textContent=`€1 = ₪${fx.EURILS.toFixed(3)} · $1 = ₪${fx.USDILS.toFixed(3)} · 1 RON = ₪${fx.RONILS.toFixed(3)}`;}
async function fetchJson(url,timeout=8000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{cache:'no-store',signal:c.signal});if(!r.ok)throw new Error(String(r.status));return await r.json();}finally{clearTimeout(t)}}
async function loadFx(){const status=$('summaryRateStatus');try{const c=JSON.parse(localStorage.getItem(FX_KEY)||'null');if(c?.rates?.EURILS){fx=c.rates;renderAll();if(status)status.textContent='🟡 מציג שער שמור ומעדכן…'}}catch(e){}
 let rates=null;
 try{const j=await fetchJson('https://api.frankfurter.app/latest?from=EUR&to=ILS,RON,USD');const ei=+j.rates?.ILS,er=+j.rates?.RON,eu=+j.rates?.USD;if(ei>0&&er>0&&eu>0)rates={EURILS:ei,RONILS:ei/er,USDILS:ei/eu};}catch(e){}
 if(!rates){try{const j=await fetchJson('https://open.er-api.com/v6/latest/EUR');const ei=+j.rates?.ILS,er=+j.rates?.RON,eu=+j.rates?.USD;if(ei>0&&er>0&&eu>0)rates={EURILS:ei,RONILS:ei/er,USDILS:ei/eu};}catch(e){}}
 if(rates){fx=rates;localStorage.setItem(FX_KEY,JSON.stringify({rates,time:Date.now()}));renderAll();if(status)status.textContent='🟢 שערי ההמרה עודכנו אונליין';}else if(fx.EURILS){if(status)status.textContent='🟡 אין עדכון כרגע · משתמש בשער האחרון שנשמר';}else{if(status)status.textContent='🔴 אין כרגע שער המרה זמין';}
}
function addExpense(){const amount=Number($('expenseAmount')?.value),currency=$('expenseCurrency')?.value||'RON',description=($('expenseDescription')?.value||'').trim();if(!(amount>0)){alert('יש להזין מחיר');return}const a=readExpenses();a.push({id:Date.now(),amount,currency,description,createdAt:new Date().toISOString()});try{writeExpenses(a)}catch(e){alert('הדפדפן חסם שמירה מקומית. יש לבדוק ש-Safari אינו במצב גלישה פרטית.');return}if($('expenseAmount'))$('expenseAmount').value='';if($('expenseDescription'))$('expenseDescription').value='';renderAll();}
function init(){const sel=$('expenseCurrency');if(sel&&!sel.querySelector('option[value="USD"]')){const o=document.createElement('option');o.value='USD';o.textContent='USD ($)';sel.insertBefore(o,sel.querySelector('option[value="ILS"]'));}const total=$('summaryGrandTotal')?.closest('.summary-row');if(total){const b=total.querySelector('b');if(b)b.textContent='סה״כ:';const note=total.querySelector('div div');if(note)note.textContent='שולם או התחייבת לשלם נכון לעכשיו';}
 const old=$('addExpenseBtn');if(old){const fresh=old.cloneNode(true);old.replaceWith(fresh);fresh.addEventListener('click',addExpense);}
 renderAll();loadFx();document.querySelector('[data-page="summary"]')?.addEventListener('click',()=>{renderAll();if(!fx.EURILS)loadFx()});window.addEventListener('storage',e=>{if(e.key===EXP_KEY||e.key===OLD_KEY)renderAll()});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
window.RomaniaSummary={render:renderAll,reloadRates:loadFx};
})();