(()=>{
'use strict';
const SYNC='https://script.google.com/macros/s/AKfycbzK3SEwT-l4TfJHmEZTgv4tzL4Ctw5AZBsskHhiKMWCtrM_Yn_gbcL7wOImsNsh8TlE/exec';
try{if(!localStorage.getItem('romania-sync-endpoint'))localStorage.setItem('romania-sync-endpoint',SYNC)}catch(e){}
function navBtn(){const nav=document.querySelector('.nav');if(!nav||nav.querySelector('[data-page="flights"]'))return;const b=document.createElement('button');b.dataset.page='flights';b.textContent='✈️ טיסות';const car=nav.querySelector('[data-page="car"]');nav.insertBefore(b,car||null)}
function buildFlights(){if(document.getElementById('page-flights'))return;const main=document.querySelector('main.wrap');if(!main)return;const s=document.createElement('section');s.id='page-flights';s.className='page';s.innerHTML=`<h1>✈️ טיסות</h1><div class="grid"><div class="card"><span class="pill">הלוך · שבת 19.9</span><h2>תל אביב → בוקרשט</h2><div class="price ltr">LY9491</div><p><b>ממריא:</b> 00:20 · נתב״ג Terminal 3<br><b>נוחת:</b> 03:05 · Bucharest Henri Coandă (OTP)<br><b>משך:</b> 2:45 שעות</p><div class="facts"><div><b>מפעילה</b><br>TAROM</div><div><b>משווקת</b><br>EL AL</div><div><b>מחלקה</b><br>Economy Classic (V)</div><div><b>כבודה</b><br>1PC</div></div><div class="ok">מושב 10E* · סטטוס הזמנה OK</div></div><div class="card"><span class="pill">חזור · רביעי 30.9</span><h2>בוקרשט → תל אביב</h2><div class="price ltr">LY574</div><p><b>ממריא:</b> 10:25 · Bucharest Henri Coandă (OTP)<br><b>נוחת:</b> 12:55 · נתב״ג Terminal 3<br><b>משך:</b> 2:30 שעות</p><div class="facts"><div><b>מפעילה</b><br>EL AL</div><div><b>משווקת</b><br>EL AL</div><div><b>מחלקה</b><br>Economy Lite (V)</div><div><b>כבודה</b><br>0PC</div></div><div class="ok">סטטוס הזמנה OK</div></div></div><div class="warn"><b>שימו לב:</b> בהזמנת Klass Wagen עדיין מופיע מספר הטיסה LY571, בעוד שכרטיס הטיסה המעודכן שסיפקת מציג את טיסת ההלוך כ-LY9491 המופעלת על ידי TAROM. כדאי לעדכן את Klass Wagen במספר הטיסה החדש כדי שה-Shuttle/איסוף יתאימו לנחיתה ב-03:05.</div>`;main.appendChild(s)}
function patchCar(){const page=document.getElementById('page-car');if(!page)return;const first=page.querySelector('.grid .card');if(first){const p=first.querySelector('p');if(p)p.innerHTML='<b>Volkswagen Tiguan Automatic</b><br>19.9 · 04:00 → 30.9 · 08:30<br>Klass Total Cover<br><span class="muted">Booking: OTP-2468182759765 · OTP-AIR</span>'}const h=page.querySelector('h1');if(h)h.textContent='🚙 רכב · Klass Wagen';}
function patchHeader(){const brand=document.querySelector('.brand');if(brand)brand.textContent='🇷🇴 רומניה 2026 · 19–30 בספטמבר';const kpis=document.querySelectorAll('.home-kpi');kpis.forEach(k=>{if(k.textContent.includes('מסלול')){const b=k.querySelector('b');if(b)b.textContent='19–30.9'}})}
function init(){navBtn();buildFlights();patchCar();patchHeader();setTimeout(patchHeader,100)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();