(()=>{
'use strict';
const SYNC='https://script.google.com/macros/s/AKfycbzK3SEwT-l4TfJHmEZTgv4tzL4Ctw5AZBsskHhiKMWCtrM_Yn_gbcL7wOImsNsh8TlE/exec';
try{localStorage.setItem('romania-sync-endpoint',SYNC)}catch(e){}
function navBtn(){const nav=document.querySelector('.nav');if(!nav)return;if(!nav.querySelector('[data-page="flights"]')){const b=document.createElement('button');b.dataset.page='flights';b.textContent='✈️ טיסות';nav.insertBefore(b,nav.querySelector('[data-page="car"]')||null)}}
function flightsHtml(){return `<h1>✈️ טיסות</h1><div class="grid"><div class="card"><span class="pill">הלוך · שבת 19.9</span><h2>תל אביב → בוקרשט</h2><div class="price ltr">LY9491</div><p><b>המראה:</b> 00:20 · נתב״ג Terminal 3<br><b>נחיתה:</b> 03:05 · Bucharest Henri Coandă (OTP)<br><b>משך:</b> 2:45 שעות</p><div class="facts"><div><b>מפעילה</b><br>TAROM</div><div><b>משווקת</b><br>EL AL</div><div><b>מחלקה</b><br>Economy Classic (V)</div><div><b>כבודה</b><br>1PC</div></div><div class="ok">מושב 10E* · סטטוס OK</div></div><div class="card"><span class="pill">חזור · רביעי 30.9</span><h2>בוקרשט → תל אביב</h2><div class="price ltr">LY574</div><p><b>המראה:</b> 10:25 · OTP<br><b>נחיתה:</b> 12:55 · נתב״ג Terminal 3<br><b>משך:</b> 2:30 שעות</p><div class="facts"><div><b>מפעילה</b><br>EL AL</div><div><b>משווקת</b><br>EL AL</div><div><b>מחלקה</b><br>Economy Lite (V)</div><div><b>כבודה</b><br>0PC</div></div><div class="ok">סטטוס OK</div></div></div><div class="card" style="margin-top:14px"><b>💳 עלות טיסות כוללת</b><div class="price ltr">₪7,035</div></div><div class="warn"><b>חשוב:</b> בהזמנת Klass Wagen עדיין מופיע LY571. טיסת ההלוך המעודכנת היא LY9491, מופעלת ע״י TAROM. לעדכן את חברת ההשכרה כדי שה-Shuttle יתאים לנחיתה ב-03:05.</div>`}
function buildFlights(){let s=document.getElementById('page-flights');if(!s){s=document.createElement('section');s.id='page-flights';s.className='page';document.querySelector('main.wrap')?.appendChild(s)}if(s)s.innerHTML=flightsHtml()}
function patchHotels(){const page=document.getElementById('page-hotels');if(!page)return;page.innerHTML=`<h1>🏨 המלונות שלנו</h1>
<div class="card"><div class="hotel-title"><div><h2 style="margin:0">Hotel Orizont · Predeal</h2><span class="pill">19–23.9 · 4 לילות</span></div><div class="price ltr">₪2,255</div></div><p><b>כתובת:</b> Trei Brazi Str. 6, 505300 Predeal, Romania<br><b>טלפון:</b> <a class="phone" dir="ltr" href="tel:+40734458554">+40 734 458 554</a></p><div class="facts"><div><b>אורחים</b><br>2 מבוגרים + 2 ילדים</div><div><b>חדרים</b><br>חדר אחד</div><div><b>צ׳ק-אין</b><br>19.9 החל מ-16:00</div><div><b>צ׳ק-אאוט</b><br>23.9 עד 12:00</div></div><div class="ok"><b>עלות:</b> ₪2,255</div><a class="btn" target="_blank" href="https://www.google.com/maps/search/?api=1&query=Hotel+Orizont+Predeal+Trei+Brazi+6">📍 ניווט למלון</a></div>
<div class="card" style="margin-top:14px"><div class="hotel-title"><div><h2 style="margin:0">Swissôtel Poiana Brașov</h2><span class="pill">23–27.9 · 4 לילות</span></div><div class="price">€1,268.70</div></div><p><b>כתובת:</b> 9 Drumul Sulinar, 500001 Brașov, Romania<br><b>טלפון:</b> <a class="phone" dir="ltr" href="tel:+40368520500">+40 368 520 500</a></p><div class="facts"><div><b>חדר</b><br>Swiss Select Apartment</div><div><b>אורחים</b><br>2 מבוגרים + 2 ילדים</div><div><b>ארוחת בוקר</b><br>כלולה</div><div><b>צ׳ק-אין / אאוט</b><br>16:00 / עד 12:00</div></div><div class="ok"><b>מחיר השהייה:</b> €1,268.70</div><div class="warn"><b>חניה:</b> €17 ללילה, בכפוף לזמינות.</div><a class="btn" target="_blank" href="https://www.google.com/maps/search/?api=1&query=Swissotel+Poiana+Brasov+9+Drumul+Sulinar">📍 ניווט למלון</a></div>
<div class="card" style="margin-top:14px"><div class="hotel-title"><div><h2 style="margin:0">Novotel Bucharest City Centre</h2><span class="pill">27–30.9 · 3 לילות</span></div><div class="price ltr">₪2,968</div></div><p><b>כתובת:</b> Calea Victoriei 37B, Sector 1, 010061 Bucharest, Romania<br><b>טלפון:</b> <a class="phone" dir="ltr" href="tel:+40213088505">+40 21 308 8505</a></p><div class="facts"><div><b>אורחים</b><br>2 מבוגרים + 2 ילדים</div><div><b>חדרים</b><br>חדר אחד</div><div><b>צ׳ק-אין</b><br>27.9 החל מ-15:00</div><div><b>צ׳ק-אאוט</b><br>30.9 בין 03:00–12:00</div></div><div class="ok"><b>עלות:</b> ₪2,968</div><a class="btn" target="_blank" href="https://www.google.com/maps/search/?api=1&query=Novotel+Bucharest+City+Centre+Calea+Victoriei+37B">📍 ניווט למלון</a></div>`}
function patchCar(){const page=document.getElementById('page-car');if(!page)return;const grid=page.querySelector('.grid');if(grid)grid.innerHTML=`<div class="card"><b>✅ הזמנה מאושרת</b><p><b>Volkswagen Tiguan Automatic</b><br><b>איסוף:</b> שבת 19.9 · 04:00 · OTP-AIR<br><b>החזרה:</b> רביעי 30.9 · 08:30 · OTP-AIR<br>Klass Total Cover<br><span class="muted">Booking: OTP-2468182759765</span></p><div class="price">€527.00</div></div><div class="card"><b>📍 Shuttle / Desk</b><p>Aleea Tuberozelor, Otopeni 075100</p><a class="btn" target="_blank" href="https://www.google.com/maps/search/?api=1&query=Aleea+Tuberozelor+Otopeni+075100">📍 ניווט</a></div><div class="card"><b>📞 24/7</b><p><a class="phone" dir="ltr" href="tel:+40374020002">+40 374 020 002</a></p><p>Visa/MasterCard פיזי על שם בעל החוזה. לאחר הנחיתה להגיע לנקודת המפגש ולהזמין Shuttle.</p><div class="warn"><b>מספר טיסה אצל Klass Wagen:</b> לעדכן מ-LY571 ל-LY9491.</div></div>`}
function patchHeader(){const brand=document.querySelector('.brand');if(brand)brand.textContent='🇷🇴 רומניה 2026 · 19–30 בספטמבר';document.title='Romania Trip 2026 · 19–30 September'}
function patchSummaryStatic(){const page=document.getElementById('page-summary');if(!page)return;const list=page.querySelector('.summary-list');if(!list)return;const swiss=list.querySelector('#sumSwiss')?.closest('.summary-row');const nov=list.querySelector('#sumNovotel')?.closest('.summary-row');const car=list.querySelector('#sumCar')?.closest('.summary-row');if(swiss)swiss.outerHTML='<div class="summary-row"><div><b>🏨 Swissôtel Poiana Brașov</b><div class="muted">23–27.9 · 4 לילות</div></div><div class="ltr">€1,268.70</div><div class="summary-ils" id="sumSwiss">—</div></div>';if(nov)nov.outerHTML='<div class="summary-row"><div><b>🏨 Novotel Bucharest City Centre</b><div class="muted">27–30.9 · 3 לילות</div></div><div class="ltr">₪2,968</div><div class="summary-ils" id="sumNovotel">₪2,968</div></div>';if(car)car.outerHTML='<div class="summary-row"><div><b>🚙 Klass Wagen</b><div class="muted">19–30.9 · Tiguan Automatic + Total Cover</div></div><div class="ltr">€527.00</div><div class="summary-ils" id="sumCar">—</div></div>';if(!document.getElementById('sumOrizontRow')){const r=document.createElement('div');r.id='sumOrizontRow';r.className='summary-row';r.innerHTML='<div><b>🏨 Hotel Orizont · Predeal</b><div class="muted">19–23.9 · 4 לילות</div></div><div class="ltr">₪2,255</div><div class="summary-ils">₪2,255</div>';list.insertBefore(r,list.firstChild)}if(!document.getElementById('sumFlightsRow')){const r=document.createElement('div');r.id='sumFlightsRow';r.className='summary-row';r.innerHTML='<div><b>✈️ טיסות</b><div class="muted">LY9491 · LY574</div></div><div class="ltr">₪7,035</div><div class="summary-ils">₪7,035</div>';list.insertBefore(r,list.querySelector('.summary-row.total'))}}
function init(){navBtn();buildFlights();patchHotels();patchCar();patchHeader();patchSummaryStatic();setTimeout(()=>{buildFlights();patchHotels();patchCar();patchHeader();patchSummaryStatic();window.RomaniaSummary?.render?.();window.renderHome?.()},250)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();