(()=>{
'use strict';
const STEP_KEY='romania-steps-by-day-v1';
const STEP_EST={
 'Salina Slănic Prahova':3500,'Piața Sfatului':3000,'Parc Aventura Brașov':5000,'Sinaia Gondola':1200,'Sania Alpină Sinaia':1500,'Dimitrie Ghica Park':3500,'Peleș Castle':4500,'Paradisul Acvatic':1500,'Bâlea Lake':2200,'Vidraru Dam':1200,'Old Town Bucharest':4000,'Fashion House Militari':4000,'Jumbo Militari':3000,'King Mihai I Park':5000,'AFI Cotroceni':4500,'Therme București':2000
};
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function activeIndex(){const tabs=[...document.querySelectorAll('#tabs .tab')];const on=tabs.findIndex(x=>x.classList.contains('on'));return on>=0?on:0}
function day(){return (typeof D!=='undefined'&&Array.isArray(D))?D[activeIndex()]:null}
function isAttraction(n,d=''){return !/(hotel|swissôtel|swissotel|novotel|orizont|otp|tlv|klass|airport|צ׳ק|צ'ק|מלון|חזרה למלון)/i.test(`${n} ${d}`)}
function readStepEdits(){try{return JSON.parse(localStorage.getItem(STEP_KEY)||'{}')||{}}catch(e){return {}}}
function steps(n,d='',di=activeIndex()){const custom=readStepEdits()?.[String(di)]?.[n];if(Number.isFinite(+custom)&&+custom>=0)return +custom;if(STEP_EST[n]!=null)return STEP_EST[n];if(!isAttraction(n,d))return 0;if(/park|פארק|old town|piața|כיכר/i.test(`${n} ${d}`))return 3500;if(/mall|afi|jumbo|outlet|fashion/i.test(`${n} ${d}`))return 3500;return 2000}
function hav(a,b){const R=6371,rad=x=>x*Math.PI/180,dLat=rad(b[1]-a[1]),dLon=rad(b[0]-a[0]),la1=rad(a[1]),la2=rad(b[1]);const z=Math.sin(dLat/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(z))}
async function routeKm(stops){const pts=stops.filter(s=>Number.isFinite(+s?.[1])&&Number.isFinite(+s?.[2]));if(pts.length<2)return 0;const coords=pts.map(s=>`${s[2]},${s[1]}`).join(';');try{const r=await fetch(`https://router.project-osrm.org/route/v1/driving/${coords}?overview=false&steps=false`,{cache:'no-store'});if(!r.ok)throw 0;const j=await r.json();if(j?.routes?.[0]?.distance)return j.routes[0].distance/1000}catch(e){}let k=0;for(let i=1;i<pts.length;i++)k+=hav([+pts[i-1][2],+pts[i-1][1]],[+pts[i][2],+pts[i][1]])*1.22;return k}
async function elevations(stops){const pts=stops.filter(s=>Number.isFinite(+s?.[1])&&Number.isFinite(+s?.[2]));if(!pts.length)return[];try{const lat=pts.map(s=>s[1]).join(','),lon=pts.map(s=>s[2]).join(',');const r=await fetch(`https://api.open-meteo.com/v1/elevation?latitude=${lat}&longitude=${lon}`,{cache:'force-cache'});if(!r.ok)throw 0;const j=await r.json(),e=Array.isArray(j.elevation)?j.elevation:[j.elevation];return pts.map((s,i)=>({name:s[0],elev:+e[i]||0}))}catch(err){return pts.map(s=>({name:s[0],elev:0}))}}
function graph(data){const vals=data.map(x=>x.elev).filter(Number.isFinite);if(!vals.length||vals.every(v=>v===0))return'<div class="tm-empty">נתוני גובה אינם זמינים כרגע.</div>';const W=760,H=190,p=28,min=Math.min(...vals),max=Math.max(...vals),range=Math.max(1,max-min),x=i=>p+(W-2*p)*(data.length===1?.5:i/(data.length-1)),y=v=>H-p-(H-2*p)*(v-min)/range;const pts=data.map((d,i)=>`${x(i)},${y(d.elev)}`).join(' ');const labels=data.map((d,i)=>`<g><circle cx="${x(i)}" cy="${y(d.elev)}" r="4"/><text x="${x(i)}" y="${Math.max(13,y(d.elev)-10)}" text-anchor="middle">${Math.round(d.elev)}m</text></g>`).join('');return`<svg class="tm-svg" viewBox="0 0 ${W} ${H}" preserveAspectRatio="none" aria-label="גרף גובה"><defs><linearGradient id="tmFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="currentColor" stop-opacity=".28"/><stop offset="1" stop-color="currentColor" stop-opacity=".03"/></linearGradient></defs><polygon points="${p},${H-p} ${pts} ${W-p},${H-p}" fill="url(#tmFill)"/><polyline points="${pts}" fill="none" stroke="currentColor" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>${labels}</svg>`}
function style(){if(document.getElementById('tripMetricsStyle'))return;const s=document.createElement('style');s.id='tripMetricsStyle';s.textContent=`
#tripMetrics{margin:14px 0}.tm-head{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin-bottom:12px}.tm-stat{background:var(--soft);border:1px solid var(--line);border-radius:14px;padding:11px}.tm-stat span{display:block;font-size:.78rem;color:var(--muted)}.tm-stat b{font-size:1.25rem}.tm-grid{display:grid;grid-template-columns:1.25fr .75fr;gap:12px}.tm-card{background:var(--card);border:1px solid var(--line);border-radius:16px;padding:14px}.tm-card h3{margin:0 0 10px}.tm-svg{width:100%;height:190px;color:var(--trans-accent,#743B46);overflow:visible}.tm-svg text{font-size:12px;fill:var(--muted)}.tm-svg circle{fill:var(--trans-accent,#743B46)}.tm-steps{display:grid;gap:8px}.tm-step{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:9px 0;border-bottom:1px solid var(--line)}.tm-step:last-child{border-bottom:0}.tm-step b{white-space:nowrap}.tm-step-input{width:92px;max-width:32vw;padding:7px 8px;border:1px solid var(--line);border-radius:9px;background:var(--card);color:inherit;font:inherit;font-weight:800;text-align:center}.tm-step-reset{border:0;background:transparent;cursor:pointer;font-size:1rem}.tm-empty{color:var(--muted);padding:18px;text-align:center}.tm-note{font-size:.78rem;color:var(--muted);margin-top:8px}@media(max-width:850px){.tm-head{grid-template-columns:repeat(3,1fr)}.tm-grid{grid-template-columns:1fr}.tm-stat{padding:9px 6px}.tm-stat b{font-size:1.05rem}.tm-svg{height:165px}}
`;document.head.appendChild(s)}
async function render(){const page=document.getElementById('page-trip'),d=day();if(!page||!d)return;style();let box=document.getElementById('tripMetrics');if(!box){box=document.createElement('section');box.id='tripMetrics';const anchor=document.getElementById('stops')?.closest('.card')||document.getElementById('stops');if(anchor)anchor.insertAdjacentElement('afterend',box);else page.appendChild(box)}const stops=Array.isArray(d.s)?d.s:[];const attrs=stops.filter(s=>isAttraction(s?.[0]||'',s?.[4]||''));const di=activeIndex();const totalSteps=attrs.reduce((a,s)=>a+steps(s[0],s[4],di),0);box.innerHTML=`<div class="tm-head"><div class="tm-stat"><span>🚗 ק״מ היום</span><b id="tmKm">טוען…</b></div><div class="tm-stat"><span>🚶 צעדים משוערים</span><b>${totalSteps.toLocaleString('he-IL')}</b></div><div class="tm-stat"><span>⛰️ טווח גובה</span><b id="tmRange">טוען…</b></div></div><div class="tm-grid"><div class="tm-card"><h3>⛰️ פרופיל גובה יומי</h3><div id="tmGraph" class="tm-empty">טוען נתוני גובה…</div></div><div class="tm-card"><h3>🚶 צעדים לפי אטרקציה</h3><div class="tm-steps">${attrs.length?attrs.map(s=>`<div class="tm-step"><span>${esc(s[0])}</span><span><input class="tm-step-input" type="number" min="0" step="100" inputmode="numeric" data-step-day="${di}" data-step-name="${esc(s[0])}" value="${steps(s[0],s[4],di)}" aria-label="צעדים ${esc(s[0])}"> <button class="tm-step-reset" type="button" data-step-reset="1" title="איפוס להערכה">↩️</button></span></div>`).join(''):'<div class="tm-empty">אין אטרקציות ביום הזה.</div>'}</div><div class="tm-note">הצעדים הם הערכה לצורך תכנון, לא מדידה בפועל.</div></div></div>`;const [km,el]=await Promise.all([routeKm(stops),elevations(stops)]);if(!document.getElementById('tripMetrics'))return;document.getElementById('tmKm').textContent=km?`${Math.round(km)} ק״מ`:'0 ק״מ';const vv=el.map(x=>x.elev).filter(v=>v>0);document.getElementById('tmRange').textContent=vv.length?`${Math.min(...vv)}–${Math.max(...vv)} מ׳`:'—';document.getElementById('tmGraph').innerHTML=graph(el)}
function schedule(){setTimeout(render,100);setTimeout(render,800)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',schedule);else schedule();
document.addEventListener('change',e=>{const inp=e.target.closest('.tm-step-input');if(!inp)return;const di=String(inp.dataset.stepDay),name=inp.dataset.stepName,val=Math.max(0,Math.round(Number(inp.value)||0)),all=readStepEdits();all[di]=all[di]||{};all[di][name]=val;localStorage.setItem(STEP_KEY,JSON.stringify(all));render()},true);
document.addEventListener('click',e=>{const reset=e.target.closest('[data-step-reset]');if(reset){const inp=reset.parentElement?.querySelector('.tm-step-input');if(inp){const all=readStepEdits(),di=String(inp.dataset.stepDay),name=inp.dataset.stepName;if(all[di])delete all[di][name];localStorage.setItem(STEP_KEY,JSON.stringify(all));render()}return}if(e.target.closest('#tabs .tab')||e.target.closest('header .nav button[data-page="trip"]'))setTimeout(render,180)},true);window.addEventListener('storage',e=>{if(e.key==='romania-itinerary-v3'||e.key===STEP_KEY)setTimeout(render,80)});
})();