(()=>{
'use strict';
const SYNC='https://script.google.com/macros/s/AKfycbzK3SEwT-l4TfJHmEZTgv4tzL4Ctw5AZBsskHhiKMWCtrM_Yn_gbcL7wOImsNsh8TlE/exec';
try{if(!localStorage.getItem('romania-sync-endpoint'))localStorage.setItem('romania-sync-endpoint',SYNC)}catch(e){}
function navBtn(){const nav=document.querySelector('.nav');if(!nav||nav.querySelector('[data-page="flights"]'))return;const b=document.createElement('button');b.dataset.page='flights';b.textContent='✈️ טיסות';const car=nav.querySelector('[data-page="car"]');nav.insertBefore(b,car||null)}
function buildFlights(){if(document.getElementById('page-flights'))return;const main=document.querySelector('main.wrap');if(!main)return;const s=document.createElement('section');s.id='page-flights';s.className='page';s.innerHTML=`<h1>✈️ טיסות</h1><div class="grid"><div class="card"><span class="pill">הלוך · שבת 19.9</span><h2>תל אביב → בוקרשט</h2><div class="price ltr">LY9491</div><p><b>ממריא:</b> 00:20 · נתב״ג Terminal 3<br><b>נוחת:</b> 03:05 · Bucharest Henri Coandă (OTP)<br><b>משך:</b> 2:45 שעות</p><div class="facts"><div><b>מפעילה</b><br>TAROM</div><div><b>משווקת</b><br>EL AL</div><div><b>מחלקה</b><br>Economy Classic (V)</div><div><b>כבודה</b><br>1PC</div></div><div class="ok">מושב 10E* · סטטוס הזמנה OK</div></div><div class="card"><span class="pill">חזור · רביעי 30.9</span><h2>בוקרשט → תל אביב</h2><div class="price ltr">LY574</div><p><b>ממריא:</b> 10:25 · Bucharest Henri Coandă (OTP)<br><b>נוחת:</b> 12:55 · נתב״ג Terminal 3<br><b>משך:</b> 2:30 שעות</p><div class="facts"><div><b>מפעילה</b><br>EL AL</div><div><b>משווקת</b><br>EL AL</div><div><b>מחלקה</b><br>Economy Lite (V)</div><div><b>כבודה</b><br>0PC</div></div><div class="ok">סטטוס הזמנה OK</div></div></div><div class="card" style="margin-top:14px"><b>💳 עלות הטיסות</b><div class="price ltr">₪7,035</div></div><div class="warn"><b>שימו לב:</b> בהזמנת Klass Wagen עדיין מופיע מספר הטיסה LY571, בעוד שכרטיס הטיסה המעודכן מציג את טיסת ההלוך כ-LY9491 המופעלת על ידי TAROM. כדאי לעדכן את Klass Wagen במספר הטיסה החדש כדי שה-Shuttle/איסוף יתאימו לנחיתה ב-03:05.</div>`;main.appendChild(s)}
function patchHotels(){const page=document.getElementById('page-hotels');if(!page||document.getElementById('hotelOrizontCard'))return;const card=document.createElement('div');card.id='hotelOrizontCard';card.className='card';card.style.marginBottom='14px';card.innerHTML=`<div class="hotel-title"><div><h2 style="margin:0">Hotel Orizont · Predeal</h2><span class="pill">19–23.9 · 4 לילות</span></div><div class="price ltr">₪2,255</div></div><p><b>כתובת:</b> Trei Brazi Str. 6, 505300 Predeal, Romania<br><b>טלפון:</b> <a class="phone" dir="ltr" href="tel:+40734458554">+40 734 458 554</a></p><div class="facts"><div><b>אורחים</b><br>2 מבוגרים + 2 ילדים</div><div><b>חדר</b><br>חדר אחד</div><div><b>צ׳ק-אין</b><br>19.9 החל מ-16:00</div><div><b>צ׳ק-אאוט</b><br>23.9 עד 12:00</div></div><div class="ok"><b>עלות:</b> ₪2,255</div><a class="btn" target="_blank" href="https://www.google.com/maps/search/?api=1&query=Hotel+Orizont+Predeal+Trei+Brazi+6">📍 ניווט למלון</a>`;const h=page.querySelector('h1');if(h)h.insertAdjacentElement('afterend',card)}
function patchCar(){const page=document.getElementById('page-car');if(!page)return;const first=page.querySelector('.grid .card');if(first){const p=first.querySelector('p');if(p)p.innerHTML='<b>Volkswagen Tiguan Automatic</b><br>19.9 · 04:00 → 30.9 · 08:30<br>Klass Total Cover<br><span class="muted">Booking: OTP-2468182759765 · OTP-AIR</span>';const price=first.querySelector('.price');if(price)price.textContent='€527.00'}const h=page.querySelector('h1');if(h)h.textContent='🚙 רכב · Klass Wagen';}
function patchSummaryRows(){const list=document.querySelector('#page-summary .summary-list');if(!list)return;if(!document.getElementById('sumOrizontRow')){const r=document.createElement('div');r.id='sumOrizontRow';r.className='summary-row';r.innerHTML='<div><b>🏨 Hotel Orizont · Predeal</b><div class="muted">4 לילות · 19–23.9</div></div><div class="ltr">₪2,255</div><div class="summary-ils" id="sumOrizont">₪2,255</div>';list.insertBefore(r,list.firstChild)}if(!document.getElementById('sumFlightsRow')){const r=document.createElement('div');r.id='sumFlightsRow';r.className='summary-row';r.innerHTML='<div><b>✈️ טיסות</b><div class="muted">LY9491 + LY574</div></div><div class="ltr">₪7,035</div><div class="summary-ils" id="sumFlights">₪7,035</div>';const total=list.querySelector('.summary-row.total');list.insertBefore(r,total||null)}}
function patchHeader(){const brand=document.querySelector('.brand');if(brand)brand.textContent='🇷🇴 רומניה 2026 · 19–30 בספטמבר';const kpis=document.querySelectorAll('.home-kpi');kpis.forEach(k=>{const b=k.querySelector('b');if(!b)return;if(k.textContent.includes('מסלול'))b.textContent='19–30.9';if(k.textContent.includes('מלונות'))b.textContent='11 לילות'})}
function init(){navBtn();buildFlights();patchHotels();patchCar();patchSummaryRows();patchHeader();setTimeout(()=>{patchHotels();patchCar();patchSummaryRows();patchHeader()},150)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();